"""GitHub Actions workflow generators.

Each `build_*` returns the canonical text for one workflow file. Output is
deterministic: sorted, alphabetical tie-breaks, fixed action versions.
"""

#  Copyright (c) 2026. Scitrera LLC. Licensed under 3-clause BSD license
#  (see LICENSE file at https://github.com/scitrera/repo-tools/blob/main/LICENSE)

from __future__ import annotations

from typing import Iterable, List

from ..version_sync.config import CiConfig, SyncConfig
from ..version_sync.discovery import manifests_for_language
from .topology import publish_order

# Pinned action versions — bumped explicitly, not picked up via floating tag.
CHECKOUT = "actions/checkout@v6"
SETUP_PYTHON = "actions/setup-python@v6"
SETUP_NODE = "actions/setup-node@v6"
PYPI_PUBLISH = "pypa/gh-action-pypi-publish@release/v1"

GENERATED_HEADER = (
    "# Generated by scitrera-repo-tools `generate-ci`. Do not edit by hand;\n"
    "# re-run the generator after editing versions.yaml. Run\n"
    "# `generate-ci` (no flags) to check for drift, `generate-ci --force` to apply.\n"
)


def _project_dir(config: SyncConfig, lang: str, project: str) -> str:
    """POSIX-style directory of `project`'s manifest, relative to repo root."""
    manifests = manifests_for_language(config, lang)
    abs_path = manifests[project]
    rel = abs_path.parent.relative_to(config.root)
    return str(rel).replace("\\", "/") or "."


def _job_id(prefix: str, project: str) -> str:
    """Job id-safe slug; project names already match `[a-z0-9-]+` in practice."""
    return f"{prefix}-{project}"


def _format_branch_list(branches: Iterable[str]) -> str:
    quoted = ", ".join(b for b in branches)
    return f"[ {quoted} ]"


def _format_paths_block(paths: Iterable[str], indent: str = "      ") -> str:
    lines = [f"{indent}- '{p}'" for p in sorted(set(paths))]
    return "\n".join(lines)


def _python_projects(config: SyncConfig) -> List[str]:
    return sorted(manifests_for_language(config, "python").keys())


def _npm_projects(config: SyncConfig) -> List[str]:
    return sorted(manifests_for_language(config, "typescript").keys())


def build_version_check(config: SyncConfig, ci: CiConfig) -> str:
    paths: List[str] = ["versions.yaml"]
    for rules in config.project_rules.values():
        for rule in rules:
            paths.append(rule.path)

    paths_block = _format_paths_block(paths)

    return f"""{GENERATED_HEADER}
name: Version Check

on:
  pull_request:
    paths:
{paths_block}

permissions:
  contents: read

jobs:
  check:
    name: sync-versions --check
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_PYTHON}
        with:
          python-version: '3.12'

      - name: Install scitrera-repo-tools
        run: pip install scitrera-repo-tools

      - name: Verify versions are in sync
        run: sync-versions --check --verbose
"""


def _python_test_job(project: str, project_dir: str, ci: CiConfig) -> str:
    py = ci.python
    matrix = ", ".join(f'"{v}"' for v in py.test_versions)
    lint_step = ""
    if py.lint == "ruff":
        lint_step = f"""\

      - name: Lint with ruff
        run: |
          pip install ruff
          ruff check .
        working-directory: {project_dir}
"""

    return f"""  test-{project}:
    name: Test {project} (py${{{{ matrix.python-version }}}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [{matrix}]
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_PYTHON}
        with:
          python-version: ${{{{ matrix.python-version }}}}
{lint_step}
      - name: Install
        run: {py.install}
        working-directory: {project_dir}

      - name: Run tests
        run: python -m pytest -v
        working-directory: {project_dir}
"""


def build_test_python(config: SyncConfig, ci: CiConfig) -> str:
    projects = _python_projects(config)
    if not projects:
        return ""

    branches_csv = ", ".join(ci.test_branches)
    jobs = "\n".join(
        _python_test_job(p, _project_dir(config, "python", p), ci) for p in projects
    )

    return f"""{GENERATED_HEADER}
name: Test (Python)

on:
  push:
    branches: [ {branches_csv} ]
  pull_request:
    branches: [ {branches_csv} ]

concurrency:
  group: test-python-${{{{ github.ref }}}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
{jobs}"""


def _npm_test_job(project: str, project_dir: str, ci: CiConfig) -> str:
    npm = ci.npm
    lint_step = ""
    if npm.lint == "tsc-noemit":
        lint_step = f"""\

      - name: Type-check
        run: npx --no-install tsc --noEmit
        working-directory: {project_dir}
"""
    elif npm.lint == "eslint":
        lint_step = f"""\

      - name: Lint
        run: npx --no-install eslint .
        working-directory: {project_dir}
"""

    return f"""  test-{project}:
    name: Test {project}
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_NODE}
        with:
          node-version: '{npm.node_version}'

      - name: Install
        run: npm ci
        working-directory: {project_dir}
{lint_step}
      - name: Run tests
        run: npm test --if-present
        working-directory: {project_dir}
"""


def build_test_npm(config: SyncConfig, ci: CiConfig) -> str:
    projects = _npm_projects(config)
    if not projects:
        return ""

    branches_csv = ", ".join(ci.test_branches)
    jobs = "\n".join(
        _npm_test_job(p, _project_dir(config, "typescript", p), ci) for p in projects
    )

    return f"""{GENERATED_HEADER}
name: Test (npm)

on:
  push:
    branches: [ {branches_csv} ]
  pull_request:
    branches: [ {branches_csv} ]

concurrency:
  group: test-npm-${{{{ github.ref }}}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
{jobs}"""


def _python_publish_job(
    project: str,
    project_dir: str,
    needs: Iterable[str],
    ci: CiConfig,
) -> str:
    py = ci.python
    needs_clause = ""
    needs_list = [f"publish-{n}" for n in needs]
    if needs_list:
        needs_csv = ", ".join(needs_list)
        needs_clause = f"    needs: [ {needs_csv} ]\n"

    return f"""  publish-{project}:
    name: Publish {project} to PyPI
    runs-on: ubuntu-latest
{needs_clause}    environment:
      name: {py.pypi_environment}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_PYTHON}
        with:
          python-version: '3.12'

      - name: Install scitrera-repo-tools + build
        run: pip install scitrera-repo-tools build

      - name: Rewrite local refs to version pins
        run: sync-versions --release

      - name: Build sdist + wheel
        run: python -m build
        working-directory: {project_dir}

      - name: Publish to PyPI (trusted publisher)
        uses: {PYPI_PUBLISH}
        with:
          packages-dir: {project_dir}/dist/
"""


def build_publish_python(config: SyncConfig, ci: CiConfig) -> str:
    order = publish_order(config, "python")
    if not order:
        return ""

    jobs = "\n".join(
        _python_publish_job(
            node.name,
            _project_dir(config, "python", node.name),
            node.needs,
            ci,
        )
        for node in order
    )

    return f"""{GENERATED_HEADER}
name: Publish (Python)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: publish-python
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
{jobs}"""


def _npm_publish_job(
    project: str,
    project_dir: str,
    needs: Iterable[str],
    ci: CiConfig,
) -> str:
    npm = ci.npm
    needs_clause = ""
    needs_list = [f"publish-{n}" for n in needs]
    if needs_list:
        needs_csv = ", ".join(needs_list)
        needs_clause = f"    needs: [ {needs_csv} ]\n"

    publish_flags = ["--access", "public"]
    if npm.use_provenance:
        publish_flags.append("--provenance")
    publish_args = " ".join(publish_flags)

    auth_env = ""
    if not npm.use_oidc:
        auth_env = """\
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
"""

    permissions = "      contents: read\n      id-token: write" if npm.use_provenance or npm.use_oidc else "      contents: read"

    return f"""  publish-{project}:
    name: Publish {project} to npm
    runs-on: ubuntu-latest
{needs_clause}    environment:
      name: {npm.npm_environment}
    permissions:
{permissions}
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_PYTHON}
        with:
          python-version: '3.12'

      - uses: {SETUP_NODE}
        with:
          node-version: '{npm.node_version}'
          registry-url: 'https://registry.npmjs.org'

      - name: Install scitrera-repo-tools
        run: pip install scitrera-repo-tools

      - name: Rewrite local refs to version pins
        run: sync-versions --release

      - name: Install dependencies
        run: npm ci
        working-directory: {project_dir}

      - name: Build
        run: npm run build --if-present
        working-directory: {project_dir}

      - name: Publish to npm
        run: npm publish {publish_args}
        working-directory: {project_dir}
{auth_env}"""


def build_publish_npm(config: SyncConfig, ci: CiConfig) -> str:
    order = publish_order(config, "typescript")
    if not order:
        return ""

    jobs = "\n".join(
        _npm_publish_job(
            node.name,
            _project_dir(config, "typescript", node.name),
            node.needs,
            ci,
        )
        for node in order
    )

    return f"""{GENERATED_HEADER}
name: Publish (npm)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: publish-npm
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
{jobs}"""


# (filename, generator) pairs in stable order.
WORKFLOW_GENERATORS = (
    ("version-check.yml", build_version_check),
    ("test-python.yml", build_test_python),
    ("test-npm.yml", build_test_npm),
    ("publish-python.yml", build_publish_python),
    ("publish-npm.yml", build_publish_npm),
)


def render_all(config: SyncConfig) -> dict:
    """Generate every workflow; empty string means 'no projects of that language'."""
    ci = config.ci
    out = {}
    for filename, fn in WORKFLOW_GENERATORS:
        out[filename] = fn(config, ci)
    return out


__all__ = [
    "GENERATED_HEADER",
    "WORKFLOW_GENERATORS",
    "build_version_check",
    "build_test_python",
    "build_test_npm",
    "build_publish_python",
    "build_publish_npm",
    "render_all",
]
