"""GitHub Actions workflow generators.

Each `build_*` returns the canonical text for one workflow file. Output is
deterministic: sorted, alphabetical tie-breaks, fixed action versions.
"""

#  Copyright (c) 2026. Scitrera LLC. Licensed under 3-clause BSD license
#  (see LICENSE file at https://github.com/scitrera/repo-tools/blob/main/LICENSE)

from __future__ import annotations

from pathlib import Path
from typing import Iterable, List, Optional

from ..compile_protos.tools import resolve_ts_package_dir
from ..version_sync.config import CiConfig, SyncConfig
from ..version_sync.discovery import manifests_for_language
from ..version_sync.normalize import normalize_python
from .topology import PublishNode, docker_order, publish_order

# Pinned action versions — bumped explicitly, not picked up via floating tag.
CHECKOUT = "actions/checkout@v6"
SETUP_PYTHON = "actions/setup-python@v6"
SETUP_NODE = "actions/setup-node@v6"
SETUP_GO = "actions/setup-go@v6"
PYPI_PUBLISH = "pypa/gh-action-pypi-publish@release/v1"
GOLANGCI_LINT_ACTION = "golangci/golangci-lint-action@v8"
DOCKER_LOGIN = "docker/login-action@v3"
DOCKER_QEMU = "docker/setup-qemu-action@v3"
DOCKER_BUILDX = "docker/setup-buildx-action@v3"
DOCKER_META = "docker/metadata-action@v5"
DOCKER_BUILD_PUSH = "docker/build-push-action@v6"
UPLOAD_ARTIFACT = "actions/upload-artifact@v7"
DOWNLOAD_ARTIFACT = "actions/download-artifact@v8"
GH_RELEASE = "softprops/action-gh-release@v3"
SETUP_UV = "astral-sh/setup-uv@v9.0.0"
SETUP_PROTOC = "arduino/setup-protoc@v3"

# Python used for jobs that need an interpreter of their own (building sdists,
# reading tomllib). Unrelated to the test matrix.
BOOTSTRAP_PYTHON = "3.12"

GENERATED_HEADER = (
    "# Generated by scitrera-repo-tools `generate-ci-gha`. Do not edit by hand;\n"
    "# re-run the generator after editing versions.yaml. Run\n"
    "# `generate-ci-gha` (no flags) to check for drift, `generate-ci-gha --force` to apply.\n"
)


def _setup_python_step(version: str = BOOTSTRAP_PYTHON, indent: str = "      ") -> str:
    return f"""{indent}- uses: {SETUP_PYTHON}
{indent}  with:
{indent}    python-version: '{version}'
"""


def _rt(ci: CiConfig, invocation: str) -> str:
    """Render a repo-tools console-script call (e.g. `sync-versions --check`).

    Under `uvx` the tool is resolved on demand from `ci.repo_tools_source`,
    matching what the `scripts/` shims do outside CI. Under `pip` the console
    script is already on PATH, so the invocation passes through untouched.
    """
    if ci.bootstrap_method == "uvx":
        return f"uvx --from '{ci.repo_tools_source}' {invocation}"
    return invocation


def _bootstrap_steps(
    ci: CiConfig,
    *,
    need_python: bool = False,
    indent: str = "      ",
) -> str:
    """Steps that must precede any `_rt(...)` invocation in a job.

    `need_python` requests an interpreter for the job's *own* use (building an
    sdist, say). It is tracked separately from the tool bootstrap because uvx
    provisions its own Python for repo-tools and the job may not need one at all.
    """
    parts: List[str] = []
    if ci.bootstrap_method == "uvx":
        parts.append(f"{indent}- name: Install uv\n{indent}  uses: {SETUP_UV}\n")
        if need_python:
            parts.append(_setup_python_step(indent=indent))
    else:
        parts.append(_setup_python_step(indent=indent))
        parts.append(
            f"{indent}- name: Install scitrera-repo-tools\n"
            f"{indent}  run: pip install {ci.repo_tools_source}\n"
        )
    return "\n".join(parts)


def _ruff_spec(config: SyncConfig) -> str:
    """`ruff` pip spec, pinned from preferred_versions.python when declared.

    An unpinned linter turns an upstream release into a red build on an
    unrelated PR, so the pin is honored from the same place every other python
    dependency is pinned.
    """
    declared = config.preferred_versions.for_language("python").get("ruff")
    if declared is None or not str(declared).strip():
        return "ruff"
    return f"ruff{normalize_python(str(declared))}"


def _project_dir(config: SyncConfig, lang: str, project: str) -> str:
    """POSIX-style directory of `project`'s manifest, relative to repo root."""
    manifests = manifests_for_language(config, lang)
    abs_path = manifests[project]
    rel = abs_path.parent.relative_to(config.root)
    return str(rel).replace("\\", "/") or "."


def _job_id(prefix: str, project: str) -> str:
    """Job id-safe slug; project names already match `[a-z0-9-]+` in practice."""
    return f"{prefix}-{project}"


def _push_branches(ci: CiConfig) -> tuple:
    """Branches whose pushes trigger CI; defaults to the PR target branches."""
    return ci.push_branches or ci.test_branches


def _format_branch_list(branches: Iterable[str]) -> str:
    quoted = ", ".join(b for b in branches)
    return f"[ {quoted} ]"


def _format_paths_block(paths: Iterable[str], indent: str = "      ") -> str:
    lines = [f"{indent}- '{p}'" for p in sorted(set(paths))]
    return "\n".join(lines)


def _python_projects(config: SyncConfig) -> List[str]:
    return sorted(manifests_for_language(config, "python").keys())


def _python_test_projects(config: SyncConfig, ci: CiConfig) -> List[str]:
    """Python projects that get a test job, honoring `ci.python.test_projects`."""
    projects = _python_projects(config)
    allow = ci.python.test_projects
    if not allow:
        return projects
    unknown = sorted(set(allow) - set(projects))
    if unknown:
        raise ValueError(
            f"ci.python.test_projects names {unknown}, which "
            f"{'is' if len(unknown) == 1 else 'are'} not python project(s); "
            f"expected one of {projects}"
        )
    return [p for p in projects if p in set(allow)]


def _npm_projects(config: SyncConfig) -> List[str]:
    return sorted(manifests_for_language(config, "typescript").keys())


def _go_projects(config: SyncConfig) -> List[str]:
    return sorted(manifests_for_language(config, "go").keys())


def _go_version(config: SyncConfig) -> str:
    """Resolve effective Go version: ci.go.go_version → go_toolchain.go → '1.25'."""
    if config.ci.go.go_version is not None:
        return config.ci.go.go_version
    if config.go_toolchain.go is not None:
        return config.go_toolchain.go
    return "1.25"


def build_version_check(config: SyncConfig, ci: CiConfig) -> str:
    paths: List[str] = ["versions.yaml"]
    for rules in config.project_rules.values():
        for rule in rules:
            paths.append(rule.path)

    paths_block = _format_paths_block(paths)

    return f"""{GENERATED_HEADER}
name: Version Check

on:
  pull_request:
    paths:
{paths_block}

permissions:
  contents: read

jobs:
  check:
    name: sync-versions --check
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

{_bootstrap_steps(ci)}
      - name: Verify versions are in sync
        run: {_rt(ci, "sync-versions --check --verbose")}
"""


def _render_steps(steps, default_dir: str, indent: str = "      ") -> str:
    """Render caller-supplied steps as a YAML block.

    Returns "" or a block that both starts and ends with a newline, matching the
    convention the surrounding job templates use for optional sections. Multi-line
    `run` bodies are emitted as a literal block scalar with every line carried to
    `indent + 4`; a line left short of that dedents out of the scalar and
    corrupts the file rather than failing visibly.
    """
    if not steps:
        return ""
    parts: List[str] = []
    for step in steps:
        wd = step.working_directory if step.working_directory is not None else default_dir
        block = f"{indent}- name: {step.name}\n"
        if step.if_expr:
            block += f"{indent}  if: {step.if_expr}\n"
        block += f"{indent}  run: |\n"
        for line in step.run.split("\n"):
            block += f"{indent}    {line}\n" if line.strip() else "\n"
        block += f"{indent}  working-directory: {wd}\n"
        parts.append(block)
    return "\n" + "\n".join(parts)


def _python_project_cfg(ci: CiConfig, project: str):
    """Per-project override record, or None when the project has no entry."""
    return ci.python.projects.get(project)


def _python_dep_closure(config: SyncConfig) -> dict:
    """Transitive in-repo python dependencies per project, in install order.

    Deliberately NOT sorted, unlike the npm closure: the result is fed straight
    to successive `pip install -e` calls, so a dependency has to appear before
    anything that requires it. `publish_order` yields leaves first, and each
    entry's own closure is already ordered, so appending preserves that.
    """
    order = publish_order(config, "python")
    direct = {n.name: list(n.needs) for n in order}
    closure: dict = {}
    for node in order:
        acc: List[str] = []
        for dep in direct[node.name]:
            for name in closure.get(dep, []) + [dep]:
                if name not in acc:
                    acc.append(name)
        closure[node.name] = acc
    return closure


def _python_local_dep_step(deps: Iterable[tuple], indent: str = "      ") -> str:
    """Editable-install the project's in-repo dependencies from the checkout.

    One step rather than one per dependency: the ordering is the only thing that
    matters and a single block keeps it visible. Runs from the repo root, so the
    paths are the same repo-relative directories used everywhere else.
    """
    deps = list(deps)
    if not deps:
        return ""
    lines = "".join(f"{indent}    pip install -e {d}\n" for _, d in deps)
    names = ", ".join(name for name, _ in deps)
    return f"""
{indent}- name: Install in-repo dependencies ({names})
{indent}  run: |
{lines}"""


def _python_test_job(
    project: str,
    project_dir: str,
    ci: CiConfig,
    ruff_spec: str = "ruff",
    local_deps: Iterable[tuple] = (),
) -> str:
    py = ci.python
    over = _python_project_cfg(ci, project)
    install = over.install if over is not None and over.install is not None else py.install
    test_command = (
        over.test_command
        if over is not None and over.test_command is not None
        else py.test_command
    )
    setup_steps = tuple(py.setup_steps) + tuple(over.setup_steps if over else ())
    extra_steps = tuple(py.extra_steps) + tuple(over.extra_steps if over else ())

    matrix = ", ".join(f'"{v}"' for v in py.test_versions)
    lint_step = ""
    if py.lint == "ruff":
        format_line = "\n          ruff format --check ." if py.format_check else ""
        lint_step = f"""\

      - name: Lint with ruff
        run: |
          pip install {ruff_spec}
          ruff check .{format_line}
        working-directory: {project_dir}
"""

    setup_block = _render_steps(setup_steps, project_dir)
    extra_block = _render_steps(extra_steps, project_dir)
    local_dep_block = _python_local_dep_step(local_deps)

    return f"""  test-{project}:
    name: Test {project} (py${{{{ matrix.python-version }}}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [{matrix}]
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_PYTHON}
        with:
          python-version: ${{{{ matrix.python-version }}}}
{setup_block}{lint_step}{local_dep_block}
      - name: Install
        run: {install}
        working-directory: {project_dir}

      - name: Run tests
        run: {test_command}
        working-directory: {project_dir}
{extra_block}"""


def build_test_python(config: SyncConfig, ci: CiConfig) -> str:
    projects = _python_test_projects(config, ci)
    if not projects:
        return ""

    branches_csv = ", ".join(ci.test_branches)
    push_csv = ", ".join(_push_branches(ci))
    ruff_spec = _ruff_spec(config)
    closure = _python_dep_closure(config) if ci.python.install_local_deps else {}
    jobs = "\n".join(
        _python_test_job(
            p,
            _project_dir(config, "python", p),
            ci,
            ruff_spec,
            local_deps=[
                (d, _project_dir(config, "python", d)) for d in closure.get(p, ())
            ],
        )
        for p in projects
    )

    return f"""{GENERATED_HEADER}
name: Test (Python)

on:
  push:
    branches: [ {push_csv} ]
  pull_request:
    branches: [ {branches_csv} ]
  workflow_call:

concurrency:
  # github.ref is stable across pushes to the same PR (refs/pull/N/merge), so
  # this still cancels a superseded run when you push again — the case where
  # cancelling is the right outcome. It deliberately does NOT collapse the
  # push and pull_request runs of one commit: that duplicate is avoided with
  # ci.push_branches instead, because a cancelled run reports as cancelled
  # rather than as success.
  group: test-python-${{{{ github.ref }}}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
{jobs}"""


def _npm_dep_closure(order) -> dict:
    """Transitive in-repo dependencies per project, from a leaves-first order.

    The closure rather than the direct edges: a package two hops down the chain
    still resolves the top package's `file:` specifier through its own
    dependency, so that build output has to be present too.
    """
    direct = {n.name: list(n.needs) for n in order}
    closure: dict = {}
    for node in order:
        acc: List[str] = []
        for dep in direct[node.name]:
            for name in closure.get(dep, []) + [dep]:
                if name not in acc:
                    acc.append(name)
        closure[node.name] = sorted(acc)
    return closure


def _npm_dist_artifact(project: str) -> str:
    return f"ts-dist-{project}"


def _npm_test_job(
    project: str,
    project_dir: str,
    ci: CiConfig,
    needs: Iterable[str] = (),
    download: Iterable[tuple] = (),
    upload: bool = False,
) -> str:
    npm = ci.npm
    lint_step = ""
    if npm.lint == "tsc-noemit":
        lint_step = f"""\

      - name: Type-check
        run: npx --no-install tsc --noEmit
        working-directory: {project_dir}
"""
    elif npm.lint == "eslint":
        lint_step = f"""\

      - name: Lint
        run: npx --no-install eslint .
        working-directory: {project_dir}
"""

    cache_with = ""
    if npm.cache:
        cache_with = f"""
          cache: 'npm'
          cache-dependency-path: {project_dir}/package-lock.json"""

    build_step = ""
    if npm.build:
        build_step = f"""
      - name: Build
        run: npm run build --if-present
        working-directory: {project_dir}
"""

    needs_clause = ""
    needs_list = [f"test-{n}" for n in needs]
    if needs_list:
        needs_clause = f"    needs: [ {', '.join(needs_list)} ]\n"

    # Downloaded before `npm ci`: npm may copy rather than symlink a `file:`
    # dependency, in which case build output that arrives afterwards never
    # reaches node_modules.
    download_steps = ""
    for dep, dep_dir in download:
        download_steps += f"""
      - name: Download {dep} build output
        uses: {DOWNLOAD_ARTIFACT}
        with:
          name: {_npm_dist_artifact(dep)}
          path: {dep_dir}/dist/
"""

    upload_step = ""
    if upload:
        upload_step = f"""
      - name: Upload build output
        uses: {UPLOAD_ARTIFACT}
        with:
          name: {_npm_dist_artifact(project)}
          path: {project_dir}/dist/
          if-no-files-found: error
          retention-days: 1
"""

    return f"""  test-{project}:
    name: Test {project}
    runs-on: ubuntu-latest
{needs_clause}    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_NODE}
        with:
          node-version: '{npm.node_version}'{cache_with}
{download_steps}
      - name: Install
        run: npm ci
        working-directory: {project_dir}
{build_step}{lint_step}
      - name: Run tests
        run: npm test --if-present
        working-directory: {project_dir}
{upload_step}"""


def _go_test_job(project: str, project_dir: str, go_version: str, ci: CiConfig) -> str:
    go = ci.go
    test_args = go.test_args
    coverage_step = ""
    if go.coverage:
        test_args = f"{test_args} -coverprofile=coverage.out -covermode=atomic"
        # `if: always()` so a failing run still yields the profile for whatever
        # did execute; `warn` rather than `error` because a package set with no
        # coverable statements legitimately produces no file.
        coverage_step = f"""
      - name: Upload coverage artifact
        if: always()
        uses: {UPLOAD_ARTIFACT}
        with:
          name: go-coverage-{project}
          path: {project_dir}/coverage.out
          if-no-files-found: warn
          retention-days: 14
"""
    return f"""  test-{project}:
    name: Test {project}
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_GO}
        with:
          go-version: '{go_version}'
          cache-dependency-path: {project_dir}/go.sum

      - name: go vet
        run: go vet ./...
        working-directory: {project_dir}

      - name: go test
        run: go test {test_args} ./...
        working-directory: {project_dir}
{coverage_step}"""


def _go_lint_job(project: str, project_dir: str, ci: CiConfig) -> str:
    go = ci.go
    return f"""  lint-{project}:
    name: Lint {project}
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_GO}
        with:
          go-version: '{_go_version_placeholder}'
          cache-dependency-path: {project_dir}/go.sum

      - name: golangci-lint
        uses: {GOLANGCI_LINT_ACTION}
        with:
          version: '{go.golangci_version}'
          working-directory: {project_dir}
          args: --timeout=5m
"""


def _go_security_job(project: str, project_dir: str, go_version: str, ci: CiConfig) -> str:
    """govulncheck for one module, filtered through the accepted-risk allow-list.

    govulncheck has no native suppression, so the scan runs with `-format json`
    and its findings are compared against `ci.go.govulncheck_ignore` here. That
    is deliberately narrower than marking the whole step non-blocking: a
    genuinely new advisory still fails the build, and only the specific IDs that
    were reviewed are waived.

    Only *called* findings gate the build. govulncheck also reports advisories
    that are merely present in the module graph but never reached; those are not
    a vulnerability in this binary and would otherwise force allow-list entries
    for code that cannot execute.
    """
    go = ci.go
    applicable = [e for e in go.govulncheck_ignore if e.applies_to(project)]
    ignore_ids = " ".join(e.id for e in applicable)
    reasons = "".join(
        f"          # {e.id}: {e.reason}\n" for e in applicable
    )
    reason_block = f"\n{reasons}" if reasons else "\n"
    return f"""  security-{project}:
    name: govulncheck {project}
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_GO}
        with:
          go-version: '{go_version}'
          cache-dependency-path: {project_dir}/go.sum

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@{go.govulncheck_version}

      - name: Run govulncheck
        working-directory: {project_dir}
        env:{reason_block}          IGNORED_ADVISORIES: "{ignore_ids}"
        run: |
          set -uo pipefail
          report="$RUNNER_TEMP/govulncheck-{project}.json"
          # Exit status is non-zero when anything is found; the JSON is what we
          # judge on, so do not let `set -e` stop us before reading it.
          govulncheck -format json ./... > "$report"
          status=$?
          if [ ! -s "$report" ]; then
            echo "::error::govulncheck produced no output (exit $status)"
            exit 1
          fi

          # A finding with a function in its trace is reachable from this module.
          called=$(jq -r 'select(has("finding")) | .finding
                          | select((.trace[0].function? // null) != null) | .osv' \
                     "$report" | sort -u)

          fail=0
          for vuln in $called; do
            if printf '%s\\n' $IGNORED_ADVISORIES | grep -qx "$vuln"; then
              echo "::notice::$vuln reachable but allow-listed (see ci.go.govulncheck_ignore)"
            else
              echo "::error::$vuln is reachable and not allow-listed — see https://pkg.go.dev/vuln/$vuln"
              fail=1
            fi
          done

          # An allow-list entry that no longer matches anything is stale: the
          # dependency was fixed or dropped, and the waiver should go with it.
          for vuln in $IGNORED_ADVISORIES; do
            if ! printf '%s\\n' $called | grep -qx "$vuln"; then
              echo "::warning::$vuln is allow-listed but no longer reachable; drop it from ci.go.govulncheck_ignore"
            fi
          done

          [ "$fail" = 0 ]
"""


# Used in the lint job f-string above to avoid name-shadowing during template expansion.
_go_version_placeholder = "__GO_VERSION__"


def build_test_go(config: SyncConfig, ci: CiConfig) -> str:
    projects = _go_projects(config)
    if not projects:
        return ""

    # A misspelled project name would scope a waiver to nothing, so the
    # advisory would keep failing the build with no indication why.
    known = set(projects)
    unknown = sorted(
        {p for e in ci.go.govulncheck_ignore for p in e.projects} - known
    )
    if unknown:
        raise ValueError(
            f"ci.go.govulncheck_ignore names unknown Go project(s) {unknown}; "
            f"expected one of {sorted(known)}"
        )

    go_version = _go_version(config)
    branches_csv = ", ".join(ci.test_branches)
    push_csv = ", ".join(_push_branches(ci))

    jobs: List[str] = []
    for p in projects:
        pdir = _project_dir(config, "go", p)
        jobs.append(_go_test_job(p, pdir, go_version, ci))
        if ci.go.lint == "golangci-lint":
            jobs.append(
                _go_lint_job(p, pdir, ci).replace(_go_version_placeholder, go_version)
            )
        if ci.go.enable_govulncheck:
            jobs.append(_go_security_job(p, pdir, go_version, ci))

    return f"""{GENERATED_HEADER}
name: Test (Go)

on:
  push:
    branches: [ {push_csv} ]
  pull_request:
    branches: [ {branches_csv} ]
  workflow_call:

concurrency:
  # github.ref is stable across pushes to the same PR (refs/pull/N/merge), so
  # this still cancels a superseded run when you push again — the case where
  # cancelling is the right outcome. It deliberately does NOT collapse the
  # push and pull_request runs of one commit: that duplicate is avoided with
  # ci.push_branches instead, because a cancelled run reports as cancelled
  # rather than as success.
  group: test-go-${{{{ github.ref }}}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
{"".join(jobs)}"""


def build_test_npm(config: SyncConfig, ci: CiConfig) -> str:
    projects = _npm_projects(config)
    if not projects:
        return ""

    branches_csv = ", ".join(ci.test_branches)
    push_csv = ", ".join(_push_branches(ci))
    dirs = {p: _project_dir(config, "typescript", p) for p in projects}

    # Threading build output between test jobs only makes sense when there is a
    # dependency graph to thread it along AND something builds. With `build`
    # off nothing produces a dist/, so the jobs stay independent and the output
    # is byte-identical to before this feature existed.
    order = publish_order(config, "typescript") if ci.npm.build else []
    closure = _npm_dep_closure(order) if order else {}
    depended_on = {dep for deps in closure.values() for dep in deps}

    if closure:
        # Toposorted so a job is always defined before the jobs that need it.
        sequence = [node.name for node in order]
    else:
        sequence = projects

    # An omitted project is pulled back in when something kept depends on it:
    # without its build output the dependent cannot be tested at all, so
    # excluding it would silently break the job it was meant to leave alone.
    allow = ci.npm.test_projects
    if allow:
        unknown = sorted(set(allow) - set(projects))
        if unknown:
            raise ValueError(
                f"ci.npm.test_projects names {unknown}, which "
                f"{'is' if len(unknown) == 1 else 'are'} not typescript "
                f"project(s); expected one of {projects}"
            )
        required = set(allow)
        for name in allow:
            required.update(closure.get(name, ()))
        sequence = [p for p in sequence if p in required]
        depended_on = {
            dep for p in sequence for dep in closure.get(p, ()) if dep in required
        }

    jobs = "\n".join(
        _npm_test_job(
            p,
            dirs[p],
            ci,
            needs=closure.get(p, ()),
            download=[(d, dirs[d]) for d in closure.get(p, ())],
            upload=p in depended_on,
        )
        for p in sequence
    )

    return f"""{GENERATED_HEADER}
name: Test (npm)

on:
  push:
    branches: [ {push_csv} ]
  pull_request:
    branches: [ {branches_csv} ]
  workflow_call:

concurrency:
  # github.ref is stable across pushes to the same PR (refs/pull/N/merge), so
  # this still cancels a superseded run when you push again — the case where
  # cancelling is the right outcome. It deliberately does NOT collapse the
  # push and pull_request runs of one commit: that duplicate is avoided with
  # ci.push_branches instead, because a cancelled run reports as cancelled
  # rather than as success.
  group: test-npm-${{{{ github.ref }}}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
{jobs}"""


def _filtered_publish_order(config: SyncConfig, lang: str, allow: tuple, where: str):
    """`publish_order` restricted to `allow`, with dangling `needs` dropped.

    An excluded project must also disappear from its dependents' `needs`, or the
    workflow references a job that was never rendered and GitHub rejects it
    outright. Dropping the edge is correct rather than merely convenient: an
    unpublished project imposes no ordering constraint on the registry.
    """
    order = publish_order(config, lang)
    if not allow:
        return order

    known = {node.name for node in order}
    unknown = sorted(set(allow) - known)
    if unknown:
        raise ValueError(
            f"{where} names {unknown}, which {'is' if len(unknown) == 1 else 'are'} "
            f"not {lang} project(s); expected one of {sorted(known)}"
        )

    keep = set(allow)
    return [
        PublishNode(name=n.name, needs=tuple(d for d in n.needs if d in keep))
        for n in order
        if n.name in keep
    ]


def _npm_published_guard(project_dir: str, indent: str = "      ") -> str:
    """Step that records whether this exact version is already on npm."""
    return f"""{indent}- name: Check whether this version is already published
{indent}  id: published
{indent}  working-directory: {project_dir}
{indent}  run: |
{indent}    set -euo pipefail
{indent}    name=$(node -p "require('./package.json').name")
{indent}    version=$(node -p "require('./package.json').version")
{indent}    if npm view "$name@$version" version >/dev/null 2>&1; then
{indent}      echo "skip=true" >> "$GITHUB_OUTPUT"
{indent}      echo "::notice::$name@$version is already on npm; skipping publish"
{indent}    else
{indent}      echo "skip=false" >> "$GITHUB_OUTPUT"
{indent}    fi
"""


def _pypi_published_guard(project_dir: str, indent: str = "      ") -> str:
    """Step that records whether this exact version is already on PyPI.

    Both `python -c` calls are one-liners on purpose: a multi-line script inside
    a `run: |` block has to carry the block's indentation, and getting that wrong
    silently dedents out of the scalar and corrupts the whole workflow file.
    """
    read_field = (
        "python -c \"import tomllib;print(tomllib.load("
        "open('pyproject.toml','rb'))['project'].get('%s',''))\""
    )
    return f"""{indent}- name: Check whether this version is already published
{indent}  id: published
{indent}  working-directory: {project_dir}
{indent}  run: |
{indent}    set -euo pipefail
{indent}    name=$({read_field % "name"})
{indent}    version=$({read_field % "version"})
{indent}    if [ -z "$version" ]; then
{indent}      echo "::error::pyproject.toml declares no static version (dynamic?); ci.python.skip_if_published cannot determine what to look up"
{indent}      exit 1
{indent}    fi
{indent}    if curl -sfL -o /dev/null "https://pypi.org/pypi/$name/$version/json"; then
{indent}      echo "skip=true" >> "$GITHUB_OUTPUT"
{indent}      echo "::notice::$name $version is already on PyPI; skipping publish"
{indent}    else
{indent}      echo "skip=false" >> "$GITHUB_OUTPUT"
{indent}    fi
"""


def _python_verify_tag_job(project: str, ci: CiConfig) -> str:
    """Gate the upload on tag ↔ versions.yaml agreement.

    Also runs `sync-versions --check`, because version-check.yml only fires on
    pull requests: a direct push to a release branch would otherwise reach a tag
    with manifests that disagree with versions.yaml. Skipped for
    workflow_dispatch runs, where there is no tag to compare against.
    """
    return f"""  verify-tag:
    name: Verify tag matches {project} version
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

{_bootstrap_steps(ci)}
      - name: Verify versions are in sync
        run: {_rt(ci, "sync-versions --check --verbose")}

      - name: Compare tag against versions.yaml
        if: github.ref_type == 'tag'
        run: |
          set -euo pipefail
          tag="${{GITHUB_REF_NAME#v}}"
          declared="$({_rt(ci, f"sync-versions --print-version {project}")})"
          if [ "$tag" != "$declared" ]; then
            echo "::error::Tag ${{GITHUB_REF_NAME}} does not match the {project} version declared in versions.yaml ($declared)"
            exit 1
          fi
          echo "Tag ${{GITHUB_REF_NAME}} matches versions.yaml ($declared)."
"""


def _python_publish_job(
    project: str,
    project_dir: str,
    needs: Iterable[str],
    ci: CiConfig,
    extra_needs: Iterable[str] = (),
) -> str:
    py = ci.python
    needs_list = list(extra_needs) + [f"publish-{n}" for n in needs]
    needs_clause = ""
    if needs_list:
        needs_csv = ", ".join(needs_list)
        needs_clause = f"    needs: [ {needs_csv} ]\n"

    upload_step = ""
    if ci.github_release:
        upload_step = f"""
      - name: Upload distributions
        uses: {UPLOAD_ARTIFACT}
        with:
          name: dist-{project}
          path: {project_dir}/dist/
          if-no-files-found: error
"""

    # The guard deliberately gates only the upload. Building and archiving still
    # run, so a skipped publish still contributes its artifact to the GitHub
    # release and the release is not silently missing a package.
    guard_step = ""
    publish_if = ""
    if py.skip_if_published:
        guard_step = "\n" + _pypi_published_guard(project_dir)
        publish_if = "        if: steps.published.outputs.skip != 'true'\n"

    return f"""  publish-{project}:
    name: Publish {project} to PyPI
    runs-on: ubuntu-latest
{needs_clause}    environment:
      name: {py.pypi_environment}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: {CHECKOUT}

{_bootstrap_steps(ci, need_python=True)}
      - name: Rewrite local refs to version pins
        run: {_rt(ci, "sync-versions --release")}

      - name: Build sdist + wheel
        run: |
          pip install build
          python -m build
        working-directory: {project_dir}
{guard_step}
      - name: Publish to PyPI (trusted publisher)
{publish_if}        uses: {PYPI_PUBLISH}
        with:
          packages-dir: {project_dir}/dist/
{upload_step}"""


def _python_github_release_job(publish_job_ids: List[str]) -> str:
    needs_csv = ", ".join(publish_job_ids)
    return f"""  github-release:
    name: Attach distributions to GitHub release
    runs-on: ubuntu-latest
    needs: [ {needs_csv} ]
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - name: Download built distributions
        uses: {DOWNLOAD_ARTIFACT}
        with:
          pattern: dist-*
          merge-multiple: true
          path: dist/

      - name: Create GitHub release
        uses: {GH_RELEASE}
        with:
          files: dist/*
          generate_release_notes: true
"""


def _go_module_path(go_mod: Path) -> Optional[str]:
    """The `module` path declared in a go.mod, or None if unreadable."""
    try:
        for line in go_mod.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("module "):
                return line[len("module "):].strip()
    except OSError:
        return None
    return None


def _go_modules(config: SyncConfig) -> List[tuple]:
    """(project, dir, module_path) for every Go module, sorted by directory.

    `dir` is POSIX-relative to the repo root; "." means the module sits at the
    root and is released by the bare `vX.Y.Z` tag.
    """
    out: List[tuple] = []
    for project, manifest in sorted(manifests_for_language(config, "go").items()):
        rel = manifest.parent.relative_to(config.root)
        as_posix = str(rel).replace("\\", "/") or "."
        out.append((project, as_posix, _go_module_path(manifest)))
    return sorted(out, key=lambda t: t[1])


def _go_module_tag_problems(modules: List[tuple]) -> List[str]:
    """Module-path/directory mismatches that make a module unreleasable.

    Go locates a nested module by *directory*: a module in `sub/` is fetched as
    `<repo-root-path>/sub` at tag `sub/vX.Y.Z`. A go.mod whose declared path does
    not end in its own directory therefore cannot be fetched under either name —
    and if it claims the repo-root path, the proxy will happily synthesize a
    phantom root module from a tree that has no go.mod, which resolves but
    carries none of the real dependencies.
    """
    problems: List[str] = []
    for project, directory, module_path in modules:
        if module_path is None:
            problems.append(f"{project}: could not read the module path from {directory}/go.mod")
            continue
        if directory == ".":
            continue
        if not module_path.endswith("/" + directory):
            problems.append(
                f"{project}: {directory}/go.mod declares module '{module_path}', but a module "
                f"in '{directory}/' is released as tag '{directory}/vX.Y.Z' and its path must "
                f"end with '/{directory}'. Either rename the module path or move go.mod."
            )
    return problems


def build_publish_go(config: SyncConfig, ci: CiConfig) -> str:
    """Reconcile per-module Go tags for a release.

    Go has no publish step: a version exists once `<dir>/vX.Y.Z` points at a
    commit. So this workflow gates on the tests and then makes those tags true,
    driven by the single root tag the release already uses.
    """
    go = ci.go
    if go.module_tags == "none":
        return ""
    modules = _go_modules(config)
    nested = [m for m in modules if m[1] != "."]
    if not nested:
        return ""

    problems = _go_module_tag_problems(modules)
    if problems:
        raise ValueError(
            "publish-go.yml cannot be generated:\n  - " + "\n  - ".join(problems)
            + "\nFix the module paths, set ci.go.module_tags: none, or add 'publish-go' "
              "to ci.skip_workflows."
        )

    push = go.module_tags == "push"
    dirs_csv = " ".join(d for _, d, _ in nested)
    perms = "write" if push else "read"
    verb = "Publish" if push else "Verify"

    if push:
        action_block = """            if [ -z "$have" ]; then
              echo "::notice::creating $tag at $sha"
              git tag "$tag" "$sha"
              new="$new $tag"
            elif [ "$have" != "$sha" ]; then
              echo "::error::$tag exists at $have but the release tag is $sha"
              bad=1
            else
              echo "$tag already correct"
            fi
          done
          if [ -n "$new" ]; then
            git push origin $new
          fi
          [ "$bad" = 0 ]"""
    else:
        action_block = """            if [ -z "$have" ]; then
              echo "::error::missing tag $tag — Go cannot resolve this module at $VERSION"
              bad=1
            elif [ "$have" != "$sha" ]; then
              echo "::error::$tag points at $have but the release tag is $sha"
              bad=1
            else
              echo "$tag ok"
            fi
          done
          [ "$bad" = 0 ]"""

    parts: List[str] = []
    gate_ids, test_jobs = _reusable_test_jobs(config, ci, "go")
    if test_jobs:
        parts.append(test_jobs)
    needs_clause = f"    needs: [ {', '.join(gate_ids)} ]\n" if gate_ids else ""

    parts.append(f"""  module-tags:
    name: {verb} Go module tags
    runs-on: ubuntu-latest
{needs_clause}    permissions:
      contents: {perms}
    steps:
      - uses: {CHECKOUT}
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: {"Reconcile" if push else "Verify"} per-module tags
        env:
          MODULE_DIRS: "{dirs_csv}"
        run: |
          set -euo pipefail
          VERSION="${{{{ github.ref_name }}}}"
          case "$VERSION" in v*) ;; *) echo "::error::expected a v-prefixed tag"; exit 1 ;; esac
          sha="$(git rev-list -n1 "$VERSION")"
          bad=0
          new=""
          for dir in $MODULE_DIRS; do
            tag="$dir/$VERSION"
            have="$(git rev-list -n1 "$tag" 2>/dev/null || true)"
{action_block}
""")

    jobs = "\n".join(parts)
    return f"""{GENERATED_HEADER}
name: Publish (Go)

on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
{jobs}"""


def build_publish_python(config: SyncConfig, ci: CiConfig) -> str:
    py = ci.python
    order = _filtered_publish_order(
        config, "python", py.publish_projects, "ci.python.publish_projects"
    )
    if not order:
        return ""

    parts: List[str] = []

    # Gates that every publish job depends on. A tag push is not revocable once
    # it lands on PyPI, so the test matrix and the tag check run first rather
    # than in a parallel workflow that a publish could race.
    gate_ids: List[str] = []
    if py.publish_requires_tests:
        test_ids, test_jobs = _reusable_test_jobs(config, ci, "python")
        if test_jobs:
            parts.append(test_jobs)
        gate_ids.extend(test_ids)
    if py.verify_tag_version is not None:
        parts.append(_python_verify_tag_job(py.verify_tag_version, ci))
        gate_ids.append("verify-tag")

    publish_ids: List[str] = []
    for node in order:
        parts.append(
            _python_publish_job(
                node.name,
                _project_dir(config, "python", node.name),
                node.needs,
                ci,
                gate_ids,
            )
        )
        publish_ids.append(f"publish-{node.name}")

    if ci.github_release:
        parts.append(_python_github_release_job(publish_ids))

    jobs = "\n".join(parts)

    return f"""{GENERATED_HEADER}
name: Publish (Python)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: publish-python
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
{jobs}"""


def _npm_needs_id_token(npm) -> bool:
    """Whether the npm publish needs an OIDC token.

    Provenance signing and trusted publishing both mint one; without the
    permission npm falls back to plain token auth, which a package configured to
    require 2FA/OIDC will reject with a misleading 404.
    """
    return npm.use_provenance or npm.use_oidc


def _npm_publish_job(
    project: str,
    project_dir: str,
    needs: Iterable[str],
    ci: CiConfig,
    extra_needs: Iterable[str] = (),
) -> str:
    npm = ci.npm
    needs_clause = ""
    needs_list = list(extra_needs) + [f"publish-{n}" for n in needs]
    if needs_list:
        needs_csv = ", ".join(needs_list)
        needs_clause = f"    needs: [ {needs_csv} ]\n"

    publish_flags = ["--access", "public"]
    if npm.use_provenance:
        publish_flags.append("--provenance")
    publish_args = " ".join(publish_flags)

    auth_env = ""
    if not npm.use_oidc:
        auth_env = """\
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
"""

    # Job-level `permissions` replaces the workflow-level block outright; it does
    # not merge. Granting id-token above and omitting it here therefore revokes
    # it, npm cannot mint an OIDC token, and provenance/trusted publishing
    # silently degrade to a token-only publish.
    permissions = (
        "      contents: read\n      id-token: write"
        if _npm_needs_id_token(npm)
        else "      contents: read"
    )

    # Runs after the build so the version it reads is the one about to ship.
    guard_step = ""
    publish_if = ""
    if npm.skip_if_published:
        guard_step = "\n" + _npm_published_guard(project_dir)
        publish_if = "        if: steps.published.outputs.skip != 'true'\n"

    return f"""  publish-{project}:
    name: Publish {project} to npm
    runs-on: ubuntu-latest
{needs_clause}    environment:
      name: {npm.npm_environment}
    permissions:
{permissions}
    steps:
      - uses: {CHECKOUT}

{_bootstrap_steps(ci)}
      - uses: {SETUP_NODE}
        with:
          node-version: '{npm.node_version}'
          registry-url: 'https://registry.npmjs.org'

      - name: Rewrite local refs to version pins
        run: {_rt(ci, "sync-versions --release")}

      - name: Install dependencies
        run: npm ci
        working-directory: {project_dir}

      - name: Build
        run: npm run build --if-present
        working-directory: {project_dir}
{guard_step}
      - name: Publish to npm
{publish_if}        run: npm publish {publish_args}
        working-directory: {project_dir}
{auth_env}"""


def build_publish_npm(config: SyncConfig, ci: CiConfig) -> str:
    order = _filtered_publish_order(
        config, "typescript", ci.npm.publish_projects, "ci.npm.publish_projects"
    )
    if not order:
        return ""

    parts: List[str] = []
    gate_ids: List[str] = []
    if ci.npm.publish_requires_tests:
        gate_ids, test_jobs = _reusable_test_jobs(config, ci, "npm")
        if test_jobs:
            parts.append(test_jobs)

    for node in order:
        parts.append(
            _npm_publish_job(
                node.name,
                _project_dir(config, "typescript", node.name),
                node.needs,
                ci,
                gate_ids,
            )
        )
    jobs = "\n".join(parts)
    workflow_perms = (
        "  contents: read\n  id-token: write"
        if _npm_needs_id_token(ci.npm)
        else "  contents: read"
    )

    return f"""{GENERATED_HEADER}
name: Publish (npm)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: publish-npm
  cancel-in-progress: false

permissions:
{workflow_perms}

jobs:
{jobs}"""


def _platform_slug(platform: str) -> str:
    """`linux/amd64` → `linux-amd64`; safe for job ids and output keys."""
    return platform.replace("/", "-")


def _image_ref_name(img) -> str:
    """Repository name this image is pushed under.

    Distinct from `img.name`, which is the descriptor key and is used for job
    ids: two descriptors may publish to the same repository under different tag
    styles, so the pushed name has to be overridable independently.
    """
    return img.image_name or img.name


def _docker_image_refs(docker_cfg, image_name: str) -> List[str]:
    """All registry refs the image gets pushed to (one per configured registry)."""
    refs: List[str] = []
    if docker_cfg.ghcr:
        refs.append(f"ghcr.io/{docker_cfg.ghcr}/{image_name}")
    if docker_cfg.dockerhub:
        refs.append(f"{docker_cfg.dockerhub}/{image_name}")
    return refs


def _docker_primary_ref(docker_cfg, image_name: str) -> str:
    """Primary ref for cascade BASE_IMAGE (GHCR preferred, else DockerHub)."""
    if docker_cfg.ghcr:
        return f"ghcr.io/{docker_cfg.ghcr}/{image_name}"
    if docker_cfg.dockerhub:
        return f"{docker_cfg.dockerhub}/{image_name}"
    raise ValueError("docker: at least one of `ghcr` or `dockerhub` must be set")


def _docker_login_steps(docker_cfg, indent: str = "      ") -> str:
    """Concatenated login steps for every configured registry."""
    parts: List[str] = []
    if docker_cfg.ghcr:
        parts.append(
            f"""{indent}- name: Login to GHCR
{indent}  uses: {DOCKER_LOGIN}
{indent}  with:
{indent}    registry: ghcr.io
{indent}    username: ${{{{ github.actor }}}}
{indent}    password: ${{{{ secrets.GITHUB_TOKEN }}}}
"""
        )
    if docker_cfg.dockerhub:
        parts.append(
            f"""{indent}- name: Login to DockerHub
{indent}  uses: {DOCKER_LOGIN}
{indent}  with:
{indent}    username: ${{{{ secrets.DOCKERHUB_USERNAME }}}}
{indent}    password: ${{{{ secrets.DOCKERHUB_TOKEN }}}}
"""
        )
    return "".join(parts)


def _version_source_step(
    version_from: Optional[str],
    ci: CiConfig,
    indent: str = "      ",
) -> str:
    """Read project version via `sync-versions --print-version`. Empty if no version_from."""
    if version_from is None:
        return ""
    read_cmd = _rt(ci, f"sync-versions --print-version {version_from}")
    return f"""{_bootstrap_steps(ci, indent=indent)}
{indent}- name: Read image version from versions.yaml
{indent}  id: imgver
{indent}  run: |
{indent}    VER=$({read_cmd})
{indent}    echo "version=$VER" >> "$GITHUB_OUTPUT"
{indent}    echo "major_minor=$(echo $VER | cut -d. -f1-2)" >> "$GITHUB_OUTPUT"

"""


def _workflow_dispatch_version_step(indent: str = "      ") -> str:
    """Optional override of tags from workflow_dispatch `version` input."""
    return f"""{indent}- name: Compute workflow_dispatch version tags
{indent}  id: ver
{indent}  if: github.event_name == 'workflow_dispatch' && inputs.version != ''
{indent}  shell: bash
{indent}  run: |
{indent}    VER="${{{{ inputs.version }}}}"
{indent}    VER="${{VER#v}}"
{indent}    echo "version=$VER" >> "$GITHUB_OUTPUT"
{indent}    echo "major_minor=$(echo $VER | cut -d. -f1-2)" >> "$GITHUB_OUTPUT"

"""


def _docker_tag_lines(tag_style: str, version_from: Optional[str]) -> List[str]:
    """Tag patterns passed to docker/metadata-action."""
    if tag_style == "dev":
        lines = [
            "type=sha,prefix=dev-",
            "type=raw,value=dev-latest",
            "type=semver,pattern={{version}},prefix=dev-",
            "type=semver,pattern={{major}}.{{minor}},prefix=dev-",
        ]
        if version_from is not None:
            lines.extend([
                "type=raw,value=dev-${{ steps.imgver.outputs.version }},enable=${{ steps.imgver.outputs.version != '' }}",
                "type=raw,value=dev-${{ steps.imgver.outputs.major_minor }},enable=${{ steps.imgver.outputs.major_minor != '' }}",
            ])
        lines.extend([
            "type=raw,value=dev-${{ steps.ver.outputs.version }},enable=${{ steps.ver.outputs.version != '' }}",
            "type=raw,value=dev-${{ steps.ver.outputs.major_minor }},enable=${{ steps.ver.outputs.major_minor != '' }}",
        ])
        return lines

    # standard
    lines = [
        "type=sha",
        "type=raw,value=latest,enable={{is_default_branch}}",
        "type=semver,pattern={{version}}",
        "type=semver,pattern={{major}}.{{minor}}",
    ]
    if version_from is not None:
        lines.extend([
            "type=raw,value=${{ steps.imgver.outputs.version }},enable=${{ steps.imgver.outputs.version != '' }}",
            "type=raw,value=${{ steps.imgver.outputs.major_minor }},enable=${{ steps.imgver.outputs.major_minor != '' }}",
        ])
    lines.extend([
        "type=raw,value=${{ steps.ver.outputs.version }},enable=${{ steps.ver.outputs.version != '' }}",
        "type=raw,value=${{ steps.ver.outputs.major_minor }},enable=${{ steps.ver.outputs.major_minor != '' }}",
        "type=raw,value=latest,enable=${{ steps.ver.outputs.version != '' }}",
    ])
    return lines


def _docker_meta_step(
    image_name: str,
    docker_cfg,
    tag_style: str,
    version_from: Optional[str],
    indent: str = "      ",
) -> str:
    """Generate docker/metadata-action step + tag patterns."""
    refs = _docker_image_refs(docker_cfg, image_name)
    images_lines = "\n".join(f"{indent}      {r}" for r in refs)
    tag_lines = _docker_tag_lines(tag_style, version_from)
    tags_block = "\n".join(f"{indent}      {t}" for t in tag_lines)
    flavor = ""
    if tag_style == "dev":
        flavor = f"""{indent}    flavor: |
{indent}      latest=false
"""

    return f"""{indent}- name: Docker metadata
{indent}  id: meta
{indent}  uses: {DOCKER_META}
{indent}  with:
{indent}    images: |
{images_lines}
{indent}    tags: |
{tags_block}
{flavor}"""


def _docker_parent_job_id(parent_node) -> str:
    """Parent's merge job in native mode, build job in qemu mode."""
    if parent_node.strategy == "native":
        return f"merge-{parent_node.name}"
    return f"build-{parent_node.name}"


def _docker_build_args(
    node,
    parent_node,
    docker_cfg,
    indent: str = "      ",
) -> str:
    """Cascade BASE_IMAGE build-arg block, or empty when no parent."""
    if parent_node is None:
        return ""
    parent_primary = _docker_primary_ref(docker_cfg, _image_ref_name(parent_node.image))
    parent_job = _docker_parent_job_id(parent_node)
    return f"""{indent}    build-args: |
{indent}      {node.image.base_image_arg}={parent_primary}:${{{{ needs.{parent_job}.outputs.base-tag }}}}
"""


def _qemu_build_job(
    node,
    parent_node,
    test_needs_csv: str,
    docker_cfg,
    ci: CiConfig,
    platforms_csv: str,
) -> str:
    """Single-job QEMU multi-arch build."""
    img = node.image
    needs_parts = []
    if test_needs_csv:
        needs_parts.append(test_needs_csv)
    if parent_node is not None:
        needs_parts.append(_docker_parent_job_id(parent_node))
    needs_clause = ""
    if needs_parts:
        needs_clause = f"    needs: [ {', '.join(needs_parts)} ]\n"

    login_steps = _docker_login_steps(docker_cfg)
    version_step = _version_source_step(img.version_from, ci)
    workflow_dispatch_step = (
        _workflow_dispatch_version_step()
        if ci.docker.enable_workflow_dispatch_version
        else ""
    )
    meta_step = _docker_meta_step(
        _image_ref_name(img), docker_cfg, img.tag_style, img.version_from
    )
    build_args = _docker_build_args(node, parent_node, docker_cfg)

    return f"""  build-{img.name}:
    name: Build {img.name} (QEMU multi-arch)
    runs-on: ubuntu-latest
{needs_clause}    permissions:
      contents: read
      packages: write
    outputs:
      base-tag: ${{{{ steps.meta.outputs.version }}}}
    steps:
      - uses: {CHECKOUT}

      - uses: {DOCKER_QEMU}

      - uses: {DOCKER_BUILDX}

{login_steps}{version_step}{workflow_dispatch_step}{meta_step}
      - name: Build and push
        uses: {DOCKER_BUILD_PUSH}
        with:
          context: {img.context}
          file: {img.dockerfile}
          platforms: {platforms_csv}
          push: ${{{{ github.event_name != 'pull_request' }}}}
          tags: ${{{{ steps.meta.outputs.tags }}}}
          labels: ${{{{ steps.meta.outputs.labels }}}}
{build_args}          cache-from: type=gha
          cache-to: type=gha,mode=max
"""


def _native_per_platform_job(
    node,
    parent_node,
    test_needs_csv: str,
    docker_cfg,
    platform: str,
    runner: str,
) -> str:
    """One per-platform native job that pushes by digest."""
    img = node.image
    slug = _platform_slug(platform)
    primary = _docker_primary_ref(docker_cfg, _image_ref_name(img))
    needs_parts = []
    if test_needs_csv:
        needs_parts.append(test_needs_csv)
    if parent_node is not None:
        needs_parts.append(_docker_parent_job_id(parent_node))
    needs_clause = ""
    if needs_parts:
        needs_clause = f"    needs: [ {', '.join(needs_parts)} ]\n"

    login_steps = _docker_login_steps(docker_cfg)
    build_args = _docker_build_args(node, parent_node, docker_cfg)

    return f"""  build-{img.name}-{slug}:
    name: Build {img.name} ({platform})
    runs-on: {runner}
{needs_clause}    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{{{ steps.build.outputs.digest }}}}
    steps:
      - uses: {CHECKOUT}

      - uses: {DOCKER_BUILDX}

{login_steps}      - name: Build and push by digest
        id: build
        uses: {DOCKER_BUILD_PUSH}
        with:
          context: {img.context}
          file: {img.dockerfile}
          platforms: {platform}
          outputs: type=image,name={primary},push-by-digest=true,name-canonical=true,push=true
{build_args}          cache-from: type=gha
          cache-to: type=gha,mode=max
"""


def _native_merge_job(
    node,
    docker_cfg,
    ci: CiConfig,
    platforms: List[str],
) -> str:
    """Combine per-platform digests into one multi-arch manifest."""
    img = node.image
    primary = _docker_primary_ref(docker_cfg, _image_ref_name(img))
    per_plat_jobs = [f"build-{img.name}-{_platform_slug(p)}" for p in platforms]
    needs_csv = ", ".join(per_plat_jobs)

    digest_args = " \\\n            ".join(
        f"{primary}@${{{{ needs.build-{img.name}-{_platform_slug(p)}.outputs.digest }}}}"
        for p in platforms
    )

    login_steps = _docker_login_steps(docker_cfg)
    version_step = _version_source_step(img.version_from, ci)
    workflow_dispatch_step = (
        _workflow_dispatch_version_step()
        if ci.docker.enable_workflow_dispatch_version
        else ""
    )
    meta_step = _docker_meta_step(
        _image_ref_name(img), docker_cfg, img.tag_style, img.version_from
    )

    return f"""  merge-{img.name}:
    name: Merge {img.name} multi-arch manifest
    runs-on: ubuntu-latest
    needs: [ {needs_csv} ]
    permissions:
      contents: read
      packages: write
    outputs:
      base-tag: ${{{{ steps.meta.outputs.version }}}}
    steps:
      - uses: {CHECKOUT}

      - uses: {DOCKER_BUILDX}

{login_steps}{version_step}{workflow_dispatch_step}{meta_step}
      - name: Create multi-arch manifest
        env:
          DOCKER_METADATA_OUTPUT_JSON: ${{{{ steps.meta.outputs.json }}}}
        run: |
          TAGS=$(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")
          eval "docker buildx imagetools create $TAGS \\
            {digest_args}"
"""


_LANG_TEST_WORKFLOW = {"python": "test-python", "npm": "test-npm", "go": "test-go"}


def _workflow_is_managed(ci: CiConfig, basename: str) -> bool:
    """Whether the generator will actually emit `<basename>.yml` for this repo."""
    if ci.only_workflows and basename not in ci.only_workflows:
        return False
    return basename not in ci.skip_workflows


def _lang_projects(config: SyncConfig, lang: str) -> List[str]:
    if lang == "python":
        return _python_test_projects(config, config.ci)
    if lang == "npm":
        return _npm_projects(config)
    return _go_projects(config)


def _reusable_test_jobs(config: SyncConfig, ci: CiConfig, lang: str) -> tuple:
    """(gate job ids, job yaml) for gating a release job on `lang`'s tests.

    Prefers `uses:` against the generated test workflow so the matrix is defined
    exactly once — we generate both sides, so the filename and job id are known
    to be correct. Falls back to inlining a copy when that workflow is not
    managed for this repo, because a `uses:` pointing at a file the generator
    does not produce is a dangling reference that fails at run time.
    """
    projects = _lang_projects(config, lang)
    if not projects:
        return [], ""
    basename = _LANG_TEST_WORKFLOW[lang]
    if _workflow_is_managed(ci, basename):
        return ["tests"], f"  tests:\n    uses: ./.github/workflows/{basename}.yml\n"
    inline, ids = _inline_test_jobs(config, ci, prereqs=(lang,))
    return ids, inline


def _inline_test_jobs(config: SyncConfig, ci: CiConfig, prereqs=None) -> tuple:
    """Return (concatenated job YAML, list of job ids) for inlined test prereqs."""
    parts: List[str] = []
    ids: List[str] = []
    test_prereqs = set(ci.docker.test_prereqs if prereqs is None else prereqs)

    if "python" in test_prereqs:
        ruff_spec = _ruff_spec(config)
        closure = _python_dep_closure(config) if ci.python.install_local_deps else {}
        for p in _python_test_projects(config, ci):
            parts.append(
                _python_test_job(
                    p,
                    _project_dir(config, "python", p),
                    ci,
                    ruff_spec,
                    local_deps=[
                        (d, _project_dir(config, "python", d))
                        for d in closure.get(p, ())
                    ],
                )
            )
            ids.append(f"test-{p}")
    if "npm" in test_prereqs:
        for p in _npm_projects(config):
            parts.append(_npm_test_job(p, _project_dir(config, "typescript", p), ci))
            ids.append(f"test-{p}")
    if "go" in test_prereqs:
        go_version = _go_version(config)
        for p in _go_projects(config):
            parts.append(_go_test_job(p, _project_dir(config, "go", p), go_version, ci))
            ids.append(f"test-{p}")

    return "\n".join(parts), ids


def build_build_docker(config: SyncConfig, ci: CiConfig) -> str:
    """Render build-docker.yml.

    Returns "" when no docker.images are configured.
    """
    if config.docker.is_empty:
        return ""
    if not config.docker.ghcr and not config.docker.dockerhub:
        raise ValueError(
            "docker: at least one of `ghcr` or `dockerhub` must be set when "
            "any docker.images are configured."
        )

    order = docker_order(config)
    docker_cfg = config.docker
    ci_docker = ci.docker

    test_yaml, test_ids = _inline_test_jobs(config, ci)
    test_needs_csv = ", ".join(test_ids)

    name_to_node = {n.name: n for n in order}
    image_jobs: List[str] = []
    for node in order:
        platforms = list(node.image.platforms or ci_docker.default_platforms)
        platforms_csv = ",".join(platforms)
        parent_node = name_to_node.get(node.needs) if node.needs else None

        if node.strategy == "qemu":
            image_jobs.append(
                _qemu_build_job(
                    node, parent_node, test_needs_csv,
                    docker_cfg, ci, platforms_csv,
                )
            )
        else:  # native
            for plat in platforms:
                runner = ci_docker.platform_runners[plat]
                image_jobs.append(
                    _native_per_platform_job(
                        node, parent_node, test_needs_csv,
                        docker_cfg, plat, runner,
                    )
                )
            image_jobs.append(
                _native_merge_job(node, docker_cfg, ci, platforms)
            )

    triggers = ["push:\n    tags:\n      - 'v*.*.*'"]
    inputs_block = ""
    if ci_docker.enable_workflow_dispatch_version:
        inputs_block = """    inputs:
      version:
        description: 'Override version (e.g. 0.1.58 or v0.1.58). Empty produces sha-only tags.'
        required: false
        type: string
"""
    triggers.append("workflow_dispatch:\n" + inputs_block.rstrip())
    if ci_docker.build_on_pr:
        triggers.append("pull_request:")
    triggers_block = "\n  ".join(triggers)

    return f"""{GENERATED_HEADER}
name: Build & push Docker images

on:
  {triggers_block}

concurrency:
  group: docker-build-${{{{ github.ref }}}}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
{test_yaml}{"".join(image_jobs)}"""


# (filename, generator) pairs in stable order.
def _proto_missing_pins(proto) -> List[str]:
    """Toolchain pins required by the enabled outputs but absent.

    A generated workflow that installs an *unpinned* compiler is worse than no
    workflow: proto artifacts embed tool versions, so CI would drift against
    developer machines and the check would fail on files nobody touched. Missing
    pins are therefore a generation-time error rather than a silent default.
    """
    tc = proto.toolchain
    missing: List[str] = []
    if proto.go is not None:
        if tc.protoc is None:
            missing.append("proto.toolchain.protoc (required by outputs.go)")
        if tc.protoc_gen_go is None:
            missing.append(
                "proto.toolchain.protoc_gen_go (required by outputs.go; set it, or "
                'declare preferred_versions.go["google.golang.org/protobuf"] to derive it)'
            )
        if proto.go.grpc and tc.protoc_gen_go_grpc is None:
            missing.append(
                "proto.toolchain.protoc_gen_go_grpc (required by outputs.go with grpc: true)"
            )
    if proto.python is not None and tc.grpcio_tools is None:
        missing.append("proto.toolchain.grpcio_tools (required by outputs.python)")
    if proto.typescript is not None and tc.proto_loader is None:
        missing.append("proto.toolchain.proto_loader (required by outputs.typescript)")
    return missing


def _proto_go_job(config: SyncConfig, ci: CiConfig) -> str:
    proto = config.proto
    tc = proto.toolchain
    plugins = [
        f"          go install google.golang.org/protobuf/cmd/protoc-gen-go@{tc.protoc_gen_go}"
    ]
    if proto.go.grpc:
        plugins.append(
            "          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc"
            f"@{tc.protoc_gen_go_grpc}"
        )
    plugins_block = "\n".join(plugins)
    return f"""  proto-check-go:
    name: compile-protos --check (go)
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_GO}
        with:
          go-version: '{_go_version(config)}'
          cache: false

      - name: Install protoc
        uses: {SETUP_PROTOC}
        with:
          version: '{tc.protoc}'
          repo-token: ${{{{ secrets.GITHUB_TOKEN }}}}

      - name: Install Go proto plugins
        run: |
{plugins_block}

{_bootstrap_steps(ci)}
      - name: Verify generated Go code is up to date
        run: {_rt(ci, "compile-protos --check --lang go")}
"""


def _proto_python_job(config: SyncConfig, ci: CiConfig) -> str:
    tc = config.proto.toolchain
    # --python pins codegen to the interpreter that actually has grpcio-tools.
    # Under the uvx bootstrap repo-tools runs in uv's own ephemeral environment,
    # where grpc_tools is not importable, so defaulting to sys.executable would
    # look for the compiler in the wrong place.
    invocation = (
        'compile-protos --check --lang python --python "$(which python)"'
    )
    return f"""  proto-check-python:
    name: compile-protos --check (python)
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

{_bootstrap_steps(ci, need_python=True)}
      - name: Install grpcio-tools
        run: pip install grpcio-tools=={tc.grpcio_tools}

      - name: Verify generated Python code is up to date
        run: {_rt(ci, invocation)}
"""


def _proto_typescript_job(config: SyncConfig, ci: CiConfig) -> str:
    # The generator binary lives in the npm package's node_modules/.bin, so the
    # same resolution the runner uses decides where `npm ci` has to run.
    pkg_dir = resolve_ts_package_dir(config.root, config.proto)
    workdir = "."
    if pkg_dir is not None:
        try:
            rel = pkg_dir.relative_to(config.root)
            workdir = str(rel).replace("\\", "/") or "."
        except ValueError:
            workdir = "."
    return f"""  proto-check-typescript:
    name: compile-protos --check (typescript)
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_NODE}
        with:
          node-version: '{ci.npm.node_version}'

      - name: Install TypeScript proto tooling
        run: npm ci
        working-directory: {workdir}

{_bootstrap_steps(ci)}
      - name: Verify generated TypeScript code is up to date
        run: {_rt(ci, "compile-protos --check --lang typescript")}
"""


def build_proto_check(config: SyncConfig, ci: CiConfig) -> str:
    """Drift check for generated protobuf/gRPC code, one job per language.

    Split per language on purpose: each job provisions only its own toolchain
    (protoc + Go plugins, or grpcio-tools, or npm), so the three run in parallel
    instead of serializing one job through every ecosystem's installer.
    """
    proto = config.proto
    if proto.is_empty:
        return ""

    missing = _proto_missing_pins(proto)
    if missing:
        raise ValueError(
            "proto-check.yml cannot be generated with unpinned tools:\n  - "
            + "\n  - ".join(missing)
            + "\nPin them, or add 'proto-check' to ci.skip_workflows to leave this "
              "workflow unmanaged."
        )

    paths: List[str] = ["versions.yaml", f"{proto.dir}/**"]
    for out in (proto.go, proto.python, proto.typescript):
        if out is not None:
            paths.append(f"{out.path}/**")

    jobs: List[str] = []
    if proto.go is not None:
        jobs.append(_proto_go_job(config, ci))
    if proto.python is not None:
        jobs.append(_proto_python_job(config, ci))
    if proto.typescript is not None:
        jobs.append(_proto_typescript_job(config, ci))

    return f"""{GENERATED_HEADER}
name: Proto Check

on:
  pull_request:
    paths:
{_format_paths_block(paths)}

concurrency:
  group: proto-check-${{{{ github.ref }}}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
{chr(10).join(jobs)}"""


WORKFLOW_GENERATORS = (
    ("version-check.yml", build_version_check),
    ("proto-check.yml", build_proto_check),
    ("test-python.yml", build_test_python),
    ("test-npm.yml", build_test_npm),
    ("test-go.yml", build_test_go),
    ("publish-go.yml", build_publish_go),
    ("publish-python.yml", build_publish_python),
    ("publish-npm.yml", build_publish_npm),
    ("build-docker.yml", build_build_docker),
)


def render_all(config: SyncConfig) -> dict:
    """Generate every workflow; empty string means 'no projects of that language'."""
    ci = config.ci
    out = {}
    for filename, fn in WORKFLOW_GENERATORS:
        out[filename] = fn(config, ci)
    return out


__all__ = [
    "GENERATED_HEADER",
    "WORKFLOW_GENERATORS",
    "build_version_check",
    "build_proto_check",
    "build_test_python",
    "build_test_npm",
    "build_test_go",
    "build_publish_go",
    "build_publish_python",
    "build_publish_npm",
    "build_build_docker",
    "render_all",
]
