"""GitHub Actions workflow generators.

Each `build_*` returns the canonical text for one workflow file. Output is
deterministic: sorted, alphabetical tie-breaks, fixed action versions.
"""

#  Copyright (c) 2026. Scitrera LLC. Licensed under 3-clause BSD license
#  (see LICENSE file at https://github.com/scitrera/repo-tools/blob/main/LICENSE)

from __future__ import annotations

from typing import Iterable, List, Optional

from ..compile_protos.tools import resolve_ts_package_dir
from ..version_sync.config import CiConfig, SyncConfig
from ..version_sync.discovery import manifests_for_language
from ..version_sync.normalize import normalize_python
from .topology import docker_order, publish_order

# Pinned action versions — bumped explicitly, not picked up via floating tag.
CHECKOUT = "actions/checkout@v6"
SETUP_PYTHON = "actions/setup-python@v6"
SETUP_NODE = "actions/setup-node@v6"
SETUP_GO = "actions/setup-go@v6"
PYPI_PUBLISH = "pypa/gh-action-pypi-publish@release/v1"
GOLANGCI_LINT_ACTION = "golangci/golangci-lint-action@v8"
DOCKER_LOGIN = "docker/login-action@v3"
DOCKER_QEMU = "docker/setup-qemu-action@v3"
DOCKER_BUILDX = "docker/setup-buildx-action@v3"
DOCKER_META = "docker/metadata-action@v5"
DOCKER_BUILD_PUSH = "docker/build-push-action@v6"
UPLOAD_ARTIFACT = "actions/upload-artifact@v7"
DOWNLOAD_ARTIFACT = "actions/download-artifact@v8"
GH_RELEASE = "softprops/action-gh-release@v3"
SETUP_UV = "astral-sh/setup-uv@v9.0.0"
SETUP_PROTOC = "arduino/setup-protoc@v3"

# Python used for jobs that need an interpreter of their own (building sdists,
# reading tomllib). Unrelated to the test matrix.
BOOTSTRAP_PYTHON = "3.12"

GENERATED_HEADER = (
    "# Generated by scitrera-repo-tools `generate-ci-gha`. Do not edit by hand;\n"
    "# re-run the generator after editing versions.yaml. Run\n"
    "# `generate-ci-gha` (no flags) to check for drift, `generate-ci-gha --force` to apply.\n"
)


def _setup_python_step(version: str = BOOTSTRAP_PYTHON, indent: str = "      ") -> str:
    return f"""{indent}- uses: {SETUP_PYTHON}
{indent}  with:
{indent}    python-version: '{version}'
"""


def _rt(ci: CiConfig, invocation: str) -> str:
    """Render a repo-tools console-script call (e.g. `sync-versions --check`).

    Under `uvx` the tool is resolved on demand from `ci.repo_tools_source`,
    matching what the `scripts/` shims do outside CI. Under `pip` the console
    script is already on PATH, so the invocation passes through untouched.
    """
    if ci.bootstrap_method == "uvx":
        return f"uvx --from '{ci.repo_tools_source}' {invocation}"
    return invocation


def _bootstrap_steps(
    ci: CiConfig,
    *,
    need_python: bool = False,
    indent: str = "      ",
) -> str:
    """Steps that must precede any `_rt(...)` invocation in a job.

    `need_python` requests an interpreter for the job's *own* use (building an
    sdist, say). It is tracked separately from the tool bootstrap because uvx
    provisions its own Python for repo-tools and the job may not need one at all.
    """
    parts: List[str] = []
    if ci.bootstrap_method == "uvx":
        parts.append(f"{indent}- name: Install uv\n{indent}  uses: {SETUP_UV}\n")
        if need_python:
            parts.append(_setup_python_step(indent=indent))
    else:
        parts.append(_setup_python_step(indent=indent))
        parts.append(
            f"{indent}- name: Install scitrera-repo-tools\n"
            f"{indent}  run: pip install {ci.repo_tools_source}\n"
        )
    return "\n".join(parts)


def _ruff_spec(config: SyncConfig) -> str:
    """`ruff` pip spec, pinned from preferred_versions.python when declared.

    An unpinned linter turns an upstream release into a red build on an
    unrelated PR, so the pin is honored from the same place every other python
    dependency is pinned.
    """
    declared = config.preferred_versions.for_language("python").get("ruff")
    if declared is None or not str(declared).strip():
        return "ruff"
    return f"ruff{normalize_python(str(declared))}"


def _project_dir(config: SyncConfig, lang: str, project: str) -> str:
    """POSIX-style directory of `project`'s manifest, relative to repo root."""
    manifests = manifests_for_language(config, lang)
    abs_path = manifests[project]
    rel = abs_path.parent.relative_to(config.root)
    return str(rel).replace("\\", "/") or "."


def _job_id(prefix: str, project: str) -> str:
    """Job id-safe slug; project names already match `[a-z0-9-]+` in practice."""
    return f"{prefix}-{project}"


def _format_branch_list(branches: Iterable[str]) -> str:
    quoted = ", ".join(b for b in branches)
    return f"[ {quoted} ]"


def _format_paths_block(paths: Iterable[str], indent: str = "      ") -> str:
    lines = [f"{indent}- '{p}'" for p in sorted(set(paths))]
    return "\n".join(lines)


def _python_projects(config: SyncConfig) -> List[str]:
    return sorted(manifests_for_language(config, "python").keys())


def _npm_projects(config: SyncConfig) -> List[str]:
    return sorted(manifests_for_language(config, "typescript").keys())


def _go_projects(config: SyncConfig) -> List[str]:
    return sorted(manifests_for_language(config, "go").keys())


def _go_version(config: SyncConfig) -> str:
    """Resolve effective Go version: ci.go.go_version → go_toolchain.go → '1.25'."""
    if config.ci.go.go_version is not None:
        return config.ci.go.go_version
    if config.go_toolchain.go is not None:
        return config.go_toolchain.go
    return "1.25"


def build_version_check(config: SyncConfig, ci: CiConfig) -> str:
    paths: List[str] = ["versions.yaml"]
    for rules in config.project_rules.values():
        for rule in rules:
            paths.append(rule.path)

    paths_block = _format_paths_block(paths)

    return f"""{GENERATED_HEADER}
name: Version Check

on:
  pull_request:
    paths:
{paths_block}

permissions:
  contents: read

jobs:
  check:
    name: sync-versions --check
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

{_bootstrap_steps(ci)}
      - name: Verify versions are in sync
        run: {_rt(ci, "sync-versions --check --verbose")}
"""


def _python_test_job(
    project: str,
    project_dir: str,
    ci: CiConfig,
    ruff_spec: str = "ruff",
) -> str:
    py = ci.python
    matrix = ", ".join(f'"{v}"' for v in py.test_versions)
    lint_step = ""
    if py.lint == "ruff":
        lint_step = f"""\

      - name: Lint with ruff
        run: |
          pip install {ruff_spec}
          ruff check .
        working-directory: {project_dir}
"""

    return f"""  test-{project}:
    name: Test {project} (py${{{{ matrix.python-version }}}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [{matrix}]
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_PYTHON}
        with:
          python-version: ${{{{ matrix.python-version }}}}
{lint_step}
      - name: Install
        run: {py.install}
        working-directory: {project_dir}

      - name: Run tests
        run: python -m pytest -v
        working-directory: {project_dir}
"""


def build_test_python(config: SyncConfig, ci: CiConfig) -> str:
    projects = _python_projects(config)
    if not projects:
        return ""

    branches_csv = ", ".join(ci.test_branches)
    ruff_spec = _ruff_spec(config)
    jobs = "\n".join(
        _python_test_job(p, _project_dir(config, "python", p), ci, ruff_spec)
        for p in projects
    )

    return f"""{GENERATED_HEADER}
name: Test (Python)

on:
  push:
    branches: [ {branches_csv} ]
  pull_request:
    branches: [ {branches_csv} ]

concurrency:
  group: test-python-${{{{ github.ref }}}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
{jobs}"""


def _npm_test_job(project: str, project_dir: str, ci: CiConfig) -> str:
    npm = ci.npm
    lint_step = ""
    if npm.lint == "tsc-noemit":
        lint_step = f"""\

      - name: Type-check
        run: npx --no-install tsc --noEmit
        working-directory: {project_dir}
"""
    elif npm.lint == "eslint":
        lint_step = f"""\

      - name: Lint
        run: npx --no-install eslint .
        working-directory: {project_dir}
"""

    return f"""  test-{project}:
    name: Test {project}
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_NODE}
        with:
          node-version: '{npm.node_version}'

      - name: Install
        run: npm ci
        working-directory: {project_dir}
{lint_step}
      - name: Run tests
        run: npm test --if-present
        working-directory: {project_dir}
"""


def _go_test_job(project: str, project_dir: str, go_version: str, ci: CiConfig) -> str:
    go = ci.go
    test_args = go.test_args
    coverage_step = ""
    if go.coverage:
        test_args = f"{test_args} -coverprofile=coverage.out -covermode=atomic"
        # `if: always()` so a failing run still yields the profile for whatever
        # did execute; `warn` rather than `error` because a package set with no
        # coverable statements legitimately produces no file.
        coverage_step = f"""
      - name: Upload coverage artifact
        if: always()
        uses: {UPLOAD_ARTIFACT}
        with:
          name: go-coverage-{project}
          path: {project_dir}/coverage.out
          if-no-files-found: warn
          retention-days: 14
"""
    return f"""  test-{project}:
    name: Test {project}
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_GO}
        with:
          go-version: '{go_version}'
          cache-dependency-path: {project_dir}/go.sum

      - name: go vet
        run: go vet ./...
        working-directory: {project_dir}

      - name: go test
        run: go test {test_args} ./...
        working-directory: {project_dir}
{coverage_step}"""


def _go_lint_job(project: str, project_dir: str, ci: CiConfig) -> str:
    go = ci.go
    return f"""  lint-{project}:
    name: Lint {project}
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_GO}
        with:
          go-version: '{_go_version_placeholder}'
          cache-dependency-path: {project_dir}/go.sum

      - name: golangci-lint
        uses: {GOLANGCI_LINT_ACTION}
        with:
          version: '{go.golangci_version}'
          working-directory: {project_dir}
          args: --timeout=5m
"""


def _go_security_job(project: str, project_dir: str, go_version: str) -> str:
    return f"""  security-{project}:
    name: govulncheck {project}
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_GO}
        with:
          go-version: '{go_version}'
          cache-dependency-path: {project_dir}/go.sum

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...
        working-directory: {project_dir}
"""


# Used in the lint job f-string above to avoid name-shadowing during template expansion.
_go_version_placeholder = "__GO_VERSION__"


def build_test_go(config: SyncConfig, ci: CiConfig) -> str:
    projects = _go_projects(config)
    if not projects:
        return ""

    go_version = _go_version(config)
    branches_csv = ", ".join(ci.test_branches)

    jobs: List[str] = []
    for p in projects:
        pdir = _project_dir(config, "go", p)
        jobs.append(_go_test_job(p, pdir, go_version, ci))
        if ci.go.lint == "golangci-lint":
            jobs.append(
                _go_lint_job(p, pdir, ci).replace(_go_version_placeholder, go_version)
            )
        if ci.go.enable_govulncheck:
            jobs.append(_go_security_job(p, pdir, go_version))

    return f"""{GENERATED_HEADER}
name: Test (Go)

on:
  push:
    branches: [ {branches_csv} ]
  pull_request:
    branches: [ {branches_csv} ]

concurrency:
  group: test-go-${{{{ github.ref }}}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
{"".join(jobs)}"""


def build_test_npm(config: SyncConfig, ci: CiConfig) -> str:
    projects = _npm_projects(config)
    if not projects:
        return ""

    branches_csv = ", ".join(ci.test_branches)
    jobs = "\n".join(
        _npm_test_job(p, _project_dir(config, "typescript", p), ci) for p in projects
    )

    return f"""{GENERATED_HEADER}
name: Test (npm)

on:
  push:
    branches: [ {branches_csv} ]
  pull_request:
    branches: [ {branches_csv} ]

concurrency:
  group: test-npm-${{{{ github.ref }}}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
{jobs}"""


def _python_verify_tag_job(project: str, ci: CiConfig) -> str:
    """Gate the upload on tag ↔ versions.yaml agreement.

    Also runs `sync-versions --check`, because version-check.yml only fires on
    pull requests: a direct push to a release branch would otherwise reach a tag
    with manifests that disagree with versions.yaml. Skipped for
    workflow_dispatch runs, where there is no tag to compare against.
    """
    return f"""  verify-tag:
    name: Verify tag matches {project} version
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

{_bootstrap_steps(ci)}
      - name: Verify versions are in sync
        run: {_rt(ci, "sync-versions --check --verbose")}

      - name: Compare tag against versions.yaml
        if: github.ref_type == 'tag'
        run: |
          set -euo pipefail
          tag="${{GITHUB_REF_NAME#v}}"
          declared="$({_rt(ci, f"sync-versions --print-version {project}")})"
          if [ "$tag" != "$declared" ]; then
            echo "::error::Tag ${{GITHUB_REF_NAME}} does not match the {project} version declared in versions.yaml ($declared)"
            exit 1
          fi
          echo "Tag ${{GITHUB_REF_NAME}} matches versions.yaml ($declared)."
"""


def _python_publish_job(
    project: str,
    project_dir: str,
    needs: Iterable[str],
    ci: CiConfig,
    extra_needs: Iterable[str] = (),
) -> str:
    py = ci.python
    needs_list = list(extra_needs) + [f"publish-{n}" for n in needs]
    needs_clause = ""
    if needs_list:
        needs_csv = ", ".join(needs_list)
        needs_clause = f"    needs: [ {needs_csv} ]\n"

    upload_step = ""
    if ci.github_release:
        upload_step = f"""
      - name: Upload distributions
        uses: {UPLOAD_ARTIFACT}
        with:
          name: dist-{project}
          path: {project_dir}/dist/
          if-no-files-found: error
"""

    return f"""  publish-{project}:
    name: Publish {project} to PyPI
    runs-on: ubuntu-latest
{needs_clause}    environment:
      name: {py.pypi_environment}
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: {CHECKOUT}

{_bootstrap_steps(ci, need_python=True)}
      - name: Rewrite local refs to version pins
        run: {_rt(ci, "sync-versions --release")}

      - name: Build sdist + wheel
        run: |
          pip install build
          python -m build
        working-directory: {project_dir}

      - name: Publish to PyPI (trusted publisher)
        uses: {PYPI_PUBLISH}
        with:
          packages-dir: {project_dir}/dist/
{upload_step}"""


def _python_github_release_job(publish_job_ids: List[str]) -> str:
    needs_csv = ", ".join(publish_job_ids)
    return f"""  github-release:
    name: Attach distributions to GitHub release
    runs-on: ubuntu-latest
    needs: [ {needs_csv} ]
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - name: Download built distributions
        uses: {DOWNLOAD_ARTIFACT}
        with:
          pattern: dist-*
          merge-multiple: true
          path: dist/

      - name: Create GitHub release
        uses: {GH_RELEASE}
        with:
          files: dist/*
          generate_release_notes: true
"""


def build_publish_python(config: SyncConfig, ci: CiConfig) -> str:
    order = publish_order(config, "python")
    if not order:
        return ""

    py = ci.python
    parts: List[str] = []

    # Gates that every publish job depends on. A tag push is not revocable once
    # it lands on PyPI, so the test matrix and the tag check run first rather
    # than in a parallel workflow that a publish could race.
    gate_ids: List[str] = []
    if py.publish_requires_tests:
        ruff_spec = _ruff_spec(config)
        for p in _python_projects(config):
            parts.append(
                _python_test_job(p, _project_dir(config, "python", p), ci, ruff_spec)
            )
            gate_ids.append(f"test-{p}")
    if py.verify_tag_version is not None:
        parts.append(_python_verify_tag_job(py.verify_tag_version, ci))
        gate_ids.append("verify-tag")

    publish_ids: List[str] = []
    for node in order:
        parts.append(
            _python_publish_job(
                node.name,
                _project_dir(config, "python", node.name),
                node.needs,
                ci,
                gate_ids,
            )
        )
        publish_ids.append(f"publish-{node.name}")

    if ci.github_release:
        parts.append(_python_github_release_job(publish_ids))

    jobs = "\n".join(parts)

    return f"""{GENERATED_HEADER}
name: Publish (Python)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: publish-python
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
{jobs}"""


def _npm_publish_job(
    project: str,
    project_dir: str,
    needs: Iterable[str],
    ci: CiConfig,
) -> str:
    npm = ci.npm
    needs_clause = ""
    needs_list = [f"publish-{n}" for n in needs]
    if needs_list:
        needs_csv = ", ".join(needs_list)
        needs_clause = f"    needs: [ {needs_csv} ]\n"

    publish_flags = ["--access", "public"]
    if npm.use_provenance:
        publish_flags.append("--provenance")
    publish_args = " ".join(publish_flags)

    auth_env = ""
    if not npm.use_oidc:
        auth_env = """\
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
"""

    permissions = "      contents: read\n      id-token: write" if npm.use_provenance or npm.use_oidc else "      contents: read"

    return f"""  publish-{project}:
    name: Publish {project} to npm
    runs-on: ubuntu-latest
{needs_clause}    environment:
      name: {npm.npm_environment}
    permissions:
{permissions}
    steps:
      - uses: {CHECKOUT}

{_bootstrap_steps(ci)}
      - uses: {SETUP_NODE}
        with:
          node-version: '{npm.node_version}'
          registry-url: 'https://registry.npmjs.org'

      - name: Rewrite local refs to version pins
        run: {_rt(ci, "sync-versions --release")}

      - name: Install dependencies
        run: npm ci
        working-directory: {project_dir}

      - name: Build
        run: npm run build --if-present
        working-directory: {project_dir}

      - name: Publish to npm
        run: npm publish {publish_args}
        working-directory: {project_dir}
{auth_env}"""


def build_publish_npm(config: SyncConfig, ci: CiConfig) -> str:
    order = publish_order(config, "typescript")
    if not order:
        return ""

    jobs = "\n".join(
        _npm_publish_job(
            node.name,
            _project_dir(config, "typescript", node.name),
            node.needs,
            ci,
        )
        for node in order
    )

    return f"""{GENERATED_HEADER}
name: Publish (npm)

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

concurrency:
  group: publish-npm
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
{jobs}"""


def _platform_slug(platform: str) -> str:
    """`linux/amd64` → `linux-amd64`; safe for job ids and output keys."""
    return platform.replace("/", "-")


def _image_ref_name(img) -> str:
    """Repository name this image is pushed under.

    Distinct from `img.name`, which is the descriptor key and is used for job
    ids: two descriptors may publish to the same repository under different tag
    styles, so the pushed name has to be overridable independently.
    """
    return img.image_name or img.name


def _docker_image_refs(docker_cfg, image_name: str) -> List[str]:
    """All registry refs the image gets pushed to (one per configured registry)."""
    refs: List[str] = []
    if docker_cfg.ghcr:
        refs.append(f"ghcr.io/{docker_cfg.ghcr}/{image_name}")
    if docker_cfg.dockerhub:
        refs.append(f"{docker_cfg.dockerhub}/{image_name}")
    return refs


def _docker_primary_ref(docker_cfg, image_name: str) -> str:
    """Primary ref for cascade BASE_IMAGE (GHCR preferred, else DockerHub)."""
    if docker_cfg.ghcr:
        return f"ghcr.io/{docker_cfg.ghcr}/{image_name}"
    if docker_cfg.dockerhub:
        return f"{docker_cfg.dockerhub}/{image_name}"
    raise ValueError("docker: at least one of `ghcr` or `dockerhub` must be set")


def _docker_login_steps(docker_cfg, indent: str = "      ") -> str:
    """Concatenated login steps for every configured registry."""
    parts: List[str] = []
    if docker_cfg.ghcr:
        parts.append(
            f"""{indent}- name: Login to GHCR
{indent}  uses: {DOCKER_LOGIN}
{indent}  with:
{indent}    registry: ghcr.io
{indent}    username: ${{{{ github.actor }}}}
{indent}    password: ${{{{ secrets.GITHUB_TOKEN }}}}
"""
        )
    if docker_cfg.dockerhub:
        parts.append(
            f"""{indent}- name: Login to DockerHub
{indent}  uses: {DOCKER_LOGIN}
{indent}  with:
{indent}    username: ${{{{ secrets.DOCKERHUB_USERNAME }}}}
{indent}    password: ${{{{ secrets.DOCKERHUB_TOKEN }}}}
"""
        )
    return "".join(parts)


def _version_source_step(
    version_from: Optional[str],
    ci: CiConfig,
    indent: str = "      ",
) -> str:
    """Read project version via `sync-versions --print-version`. Empty if no version_from."""
    if version_from is None:
        return ""
    read_cmd = _rt(ci, f"sync-versions --print-version {version_from}")
    return f"""{_bootstrap_steps(ci, indent=indent)}
{indent}- name: Read image version from versions.yaml
{indent}  id: imgver
{indent}  run: |
{indent}    VER=$({read_cmd})
{indent}    echo "version=$VER" >> "$GITHUB_OUTPUT"
{indent}    echo "major_minor=$(echo $VER | cut -d. -f1-2)" >> "$GITHUB_OUTPUT"

"""


def _workflow_dispatch_version_step(indent: str = "      ") -> str:
    """Optional override of tags from workflow_dispatch `version` input."""
    return f"""{indent}- name: Compute workflow_dispatch version tags
{indent}  id: ver
{indent}  if: github.event_name == 'workflow_dispatch' && inputs.version != ''
{indent}  shell: bash
{indent}  run: |
{indent}    VER="${{{{ inputs.version }}}}"
{indent}    VER="${{VER#v}}"
{indent}    echo "version=$VER" >> "$GITHUB_OUTPUT"
{indent}    echo "major_minor=$(echo $VER | cut -d. -f1-2)" >> "$GITHUB_OUTPUT"

"""


def _docker_tag_lines(tag_style: str, version_from: Optional[str]) -> List[str]:
    """Tag patterns passed to docker/metadata-action."""
    if tag_style == "dev":
        lines = [
            "type=sha,prefix=dev-",
            "type=raw,value=dev-latest",
            "type=semver,pattern={{version}},prefix=dev-",
            "type=semver,pattern={{major}}.{{minor}},prefix=dev-",
        ]
        if version_from is not None:
            lines.extend([
                "type=raw,value=dev-${{ steps.imgver.outputs.version }},enable=${{ steps.imgver.outputs.version != '' }}",
                "type=raw,value=dev-${{ steps.imgver.outputs.major_minor }},enable=${{ steps.imgver.outputs.major_minor != '' }}",
            ])
        lines.extend([
            "type=raw,value=dev-${{ steps.ver.outputs.version }},enable=${{ steps.ver.outputs.version != '' }}",
            "type=raw,value=dev-${{ steps.ver.outputs.major_minor }},enable=${{ steps.ver.outputs.major_minor != '' }}",
        ])
        return lines

    # standard
    lines = [
        "type=sha",
        "type=raw,value=latest,enable={{is_default_branch}}",
        "type=semver,pattern={{version}}",
        "type=semver,pattern={{major}}.{{minor}}",
    ]
    if version_from is not None:
        lines.extend([
            "type=raw,value=${{ steps.imgver.outputs.version }},enable=${{ steps.imgver.outputs.version != '' }}",
            "type=raw,value=${{ steps.imgver.outputs.major_minor }},enable=${{ steps.imgver.outputs.major_minor != '' }}",
        ])
    lines.extend([
        "type=raw,value=${{ steps.ver.outputs.version }},enable=${{ steps.ver.outputs.version != '' }}",
        "type=raw,value=${{ steps.ver.outputs.major_minor }},enable=${{ steps.ver.outputs.major_minor != '' }}",
        "type=raw,value=latest,enable=${{ steps.ver.outputs.version != '' }}",
    ])
    return lines


def _docker_meta_step(
    image_name: str,
    docker_cfg,
    tag_style: str,
    version_from: Optional[str],
    indent: str = "      ",
) -> str:
    """Generate docker/metadata-action step + tag patterns."""
    refs = _docker_image_refs(docker_cfg, image_name)
    images_lines = "\n".join(f"{indent}      {r}" for r in refs)
    tag_lines = _docker_tag_lines(tag_style, version_from)
    tags_block = "\n".join(f"{indent}      {t}" for t in tag_lines)
    flavor = ""
    if tag_style == "dev":
        flavor = f"""{indent}    flavor: |
{indent}      latest=false
"""

    return f"""{indent}- name: Docker metadata
{indent}  id: meta
{indent}  uses: {DOCKER_META}
{indent}  with:
{indent}    images: |
{images_lines}
{indent}    tags: |
{tags_block}
{flavor}"""


def _docker_parent_job_id(parent_node) -> str:
    """Parent's merge job in native mode, build job in qemu mode."""
    if parent_node.strategy == "native":
        return f"merge-{parent_node.name}"
    return f"build-{parent_node.name}"


def _docker_build_args(
    node,
    parent_node,
    docker_cfg,
    indent: str = "      ",
) -> str:
    """Cascade BASE_IMAGE build-arg block, or empty when no parent."""
    if parent_node is None:
        return ""
    parent_primary = _docker_primary_ref(docker_cfg, _image_ref_name(parent_node.image))
    parent_job = _docker_parent_job_id(parent_node)
    return f"""{indent}    build-args: |
{indent}      {node.image.base_image_arg}={parent_primary}:${{{{ needs.{parent_job}.outputs.base-tag }}}}
"""


def _qemu_build_job(
    node,
    parent_node,
    test_needs_csv: str,
    docker_cfg,
    ci: CiConfig,
    platforms_csv: str,
) -> str:
    """Single-job QEMU multi-arch build."""
    img = node.image
    needs_parts = []
    if test_needs_csv:
        needs_parts.append(test_needs_csv)
    if parent_node is not None:
        needs_parts.append(_docker_parent_job_id(parent_node))
    needs_clause = ""
    if needs_parts:
        needs_clause = f"    needs: [ {', '.join(needs_parts)} ]\n"

    login_steps = _docker_login_steps(docker_cfg)
    version_step = _version_source_step(img.version_from, ci)
    workflow_dispatch_step = (
        _workflow_dispatch_version_step()
        if ci.docker.enable_workflow_dispatch_version
        else ""
    )
    meta_step = _docker_meta_step(
        _image_ref_name(img), docker_cfg, img.tag_style, img.version_from
    )
    build_args = _docker_build_args(node, parent_node, docker_cfg)

    return f"""  build-{img.name}:
    name: Build {img.name} (QEMU multi-arch)
    runs-on: ubuntu-latest
{needs_clause}    permissions:
      contents: read
      packages: write
    outputs:
      base-tag: ${{{{ steps.meta.outputs.version }}}}
    steps:
      - uses: {CHECKOUT}

      - uses: {DOCKER_QEMU}

      - uses: {DOCKER_BUILDX}

{login_steps}{version_step}{workflow_dispatch_step}{meta_step}
      - name: Build and push
        uses: {DOCKER_BUILD_PUSH}
        with:
          context: {img.context}
          file: {img.dockerfile}
          platforms: {platforms_csv}
          push: ${{{{ github.event_name != 'pull_request' }}}}
          tags: ${{{{ steps.meta.outputs.tags }}}}
          labels: ${{{{ steps.meta.outputs.labels }}}}
{build_args}          cache-from: type=gha
          cache-to: type=gha,mode=max
"""


def _native_per_platform_job(
    node,
    parent_node,
    test_needs_csv: str,
    docker_cfg,
    platform: str,
    runner: str,
) -> str:
    """One per-platform native job that pushes by digest."""
    img = node.image
    slug = _platform_slug(platform)
    primary = _docker_primary_ref(docker_cfg, _image_ref_name(img))
    needs_parts = []
    if test_needs_csv:
        needs_parts.append(test_needs_csv)
    if parent_node is not None:
        needs_parts.append(_docker_parent_job_id(parent_node))
    needs_clause = ""
    if needs_parts:
        needs_clause = f"    needs: [ {', '.join(needs_parts)} ]\n"

    login_steps = _docker_login_steps(docker_cfg)
    build_args = _docker_build_args(node, parent_node, docker_cfg)

    return f"""  build-{img.name}-{slug}:
    name: Build {img.name} ({platform})
    runs-on: {runner}
{needs_clause}    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{{{ steps.build.outputs.digest }}}}
    steps:
      - uses: {CHECKOUT}

      - uses: {DOCKER_BUILDX}

{login_steps}      - name: Build and push by digest
        id: build
        uses: {DOCKER_BUILD_PUSH}
        with:
          context: {img.context}
          file: {img.dockerfile}
          platforms: {platform}
          outputs: type=image,name={primary},push-by-digest=true,name-canonical=true,push=true
{build_args}          cache-from: type=gha
          cache-to: type=gha,mode=max
"""


def _native_merge_job(
    node,
    docker_cfg,
    ci: CiConfig,
    platforms: List[str],
) -> str:
    """Combine per-platform digests into one multi-arch manifest."""
    img = node.image
    primary = _docker_primary_ref(docker_cfg, _image_ref_name(img))
    per_plat_jobs = [f"build-{img.name}-{_platform_slug(p)}" for p in platforms]
    needs_csv = ", ".join(per_plat_jobs)

    digest_args = " \\\n            ".join(
        f"{primary}@${{{{ needs.build-{img.name}-{_platform_slug(p)}.outputs.digest }}}}"
        for p in platforms
    )

    login_steps = _docker_login_steps(docker_cfg)
    version_step = _version_source_step(img.version_from, ci)
    workflow_dispatch_step = (
        _workflow_dispatch_version_step()
        if ci.docker.enable_workflow_dispatch_version
        else ""
    )
    meta_step = _docker_meta_step(
        _image_ref_name(img), docker_cfg, img.tag_style, img.version_from
    )

    return f"""  merge-{img.name}:
    name: Merge {img.name} multi-arch manifest
    runs-on: ubuntu-latest
    needs: [ {needs_csv} ]
    permissions:
      contents: read
      packages: write
    outputs:
      base-tag: ${{{{ steps.meta.outputs.version }}}}
    steps:
      - uses: {CHECKOUT}

      - uses: {DOCKER_BUILDX}

{login_steps}{version_step}{workflow_dispatch_step}{meta_step}
      - name: Create multi-arch manifest
        env:
          DOCKER_METADATA_OUTPUT_JSON: ${{{{ steps.meta.outputs.json }}}}
        run: |
          TAGS=$(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON")
          eval "docker buildx imagetools create $TAGS \\
            {digest_args}"
"""


def _inline_test_jobs(config: SyncConfig, ci: CiConfig) -> tuple:
    """Return (concatenated job YAML, list of job ids) for inlined test prereqs."""
    parts: List[str] = []
    ids: List[str] = []
    test_prereqs = set(ci.docker.test_prereqs)

    if "python" in test_prereqs:
        ruff_spec = _ruff_spec(config)
        for p in _python_projects(config):
            parts.append(
                _python_test_job(p, _project_dir(config, "python", p), ci, ruff_spec)
            )
            ids.append(f"test-{p}")
    if "npm" in test_prereqs:
        for p in _npm_projects(config):
            parts.append(_npm_test_job(p, _project_dir(config, "typescript", p), ci))
            ids.append(f"test-{p}")
    if "go" in test_prereqs:
        go_version = _go_version(config)
        for p in _go_projects(config):
            parts.append(_go_test_job(p, _project_dir(config, "go", p), go_version, ci))
            ids.append(f"test-{p}")

    return "\n".join(parts), ids


def build_build_docker(config: SyncConfig, ci: CiConfig) -> str:
    """Render build-docker.yml.

    Returns "" when no docker.images are configured.
    """
    if config.docker.is_empty:
        return ""
    if not config.docker.ghcr and not config.docker.dockerhub:
        raise ValueError(
            "docker: at least one of `ghcr` or `dockerhub` must be set when "
            "any docker.images are configured."
        )

    order = docker_order(config)
    docker_cfg = config.docker
    ci_docker = ci.docker

    test_yaml, test_ids = _inline_test_jobs(config, ci)
    test_needs_csv = ", ".join(test_ids)

    name_to_node = {n.name: n for n in order}
    image_jobs: List[str] = []
    for node in order:
        platforms = list(node.image.platforms or ci_docker.default_platforms)
        platforms_csv = ",".join(platforms)
        parent_node = name_to_node.get(node.needs) if node.needs else None

        if node.strategy == "qemu":
            image_jobs.append(
                _qemu_build_job(
                    node, parent_node, test_needs_csv,
                    docker_cfg, ci, platforms_csv,
                )
            )
        else:  # native
            for plat in platforms:
                runner = ci_docker.platform_runners[plat]
                image_jobs.append(
                    _native_per_platform_job(
                        node, parent_node, test_needs_csv,
                        docker_cfg, plat, runner,
                    )
                )
            image_jobs.append(
                _native_merge_job(node, docker_cfg, ci, platforms)
            )

    triggers = ["push:\n    tags:\n      - 'v*.*.*'"]
    inputs_block = ""
    if ci_docker.enable_workflow_dispatch_version:
        inputs_block = """    inputs:
      version:
        description: 'Override version (e.g. 0.1.58 or v0.1.58). Empty produces sha-only tags.'
        required: false
        type: string
"""
    triggers.append("workflow_dispatch:\n" + inputs_block.rstrip())
    if ci_docker.build_on_pr:
        triggers.append("pull_request:")
    triggers_block = "\n  ".join(triggers)

    return f"""{GENERATED_HEADER}
name: Build & push Docker images

on:
  {triggers_block}

concurrency:
  group: docker-build-${{{{ github.ref }}}}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
{test_yaml}{"".join(image_jobs)}"""


# (filename, generator) pairs in stable order.
def _proto_missing_pins(proto) -> List[str]:
    """Toolchain pins required by the enabled outputs but absent.

    A generated workflow that installs an *unpinned* compiler is worse than no
    workflow: proto artifacts embed tool versions, so CI would drift against
    developer machines and the check would fail on files nobody touched. Missing
    pins are therefore a generation-time error rather than a silent default.
    """
    tc = proto.toolchain
    missing: List[str] = []
    if proto.go is not None:
        if tc.protoc is None:
            missing.append("proto.toolchain.protoc (required by outputs.go)")
        if tc.protoc_gen_go is None:
            missing.append(
                "proto.toolchain.protoc_gen_go (required by outputs.go; set it, or "
                'declare preferred_versions.go["google.golang.org/protobuf"] to derive it)'
            )
        if proto.go.grpc and tc.protoc_gen_go_grpc is None:
            missing.append(
                "proto.toolchain.protoc_gen_go_grpc (required by outputs.go with grpc: true)"
            )
    if proto.python is not None and tc.grpcio_tools is None:
        missing.append("proto.toolchain.grpcio_tools (required by outputs.python)")
    if proto.typescript is not None and tc.proto_loader is None:
        missing.append("proto.toolchain.proto_loader (required by outputs.typescript)")
    return missing


def _proto_go_job(config: SyncConfig, ci: CiConfig) -> str:
    proto = config.proto
    tc = proto.toolchain
    plugins = [
        f"          go install google.golang.org/protobuf/cmd/protoc-gen-go@{tc.protoc_gen_go}"
    ]
    if proto.go.grpc:
        plugins.append(
            "          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc"
            f"@{tc.protoc_gen_go_grpc}"
        )
    plugins_block = "\n".join(plugins)
    return f"""  proto-check-go:
    name: compile-protos --check (go)
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_GO}
        with:
          go-version: '{_go_version(config)}'
          cache: false

      - name: Install protoc
        uses: {SETUP_PROTOC}
        with:
          version: '{tc.protoc}'
          repo-token: ${{{{ secrets.GITHUB_TOKEN }}}}

      - name: Install Go proto plugins
        run: |
{plugins_block}

{_bootstrap_steps(ci)}
      - name: Verify generated Go code is up to date
        run: {_rt(ci, "compile-protos --check --lang go")}
"""


def _proto_python_job(config: SyncConfig, ci: CiConfig) -> str:
    tc = config.proto.toolchain
    # --python pins codegen to the interpreter that actually has grpcio-tools.
    # Under the uvx bootstrap repo-tools runs in uv's own ephemeral environment,
    # where grpc_tools is not importable, so defaulting to sys.executable would
    # look for the compiler in the wrong place.
    invocation = (
        'compile-protos --check --lang python --python "$(which python)"'
    )
    return f"""  proto-check-python:
    name: compile-protos --check (python)
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

{_bootstrap_steps(ci, need_python=True)}
      - name: Install grpcio-tools
        run: pip install grpcio-tools=={tc.grpcio_tools}

      - name: Verify generated Python code is up to date
        run: {_rt(ci, invocation)}
"""


def _proto_typescript_job(config: SyncConfig, ci: CiConfig) -> str:
    # The generator binary lives in the npm package's node_modules/.bin, so the
    # same resolution the runner uses decides where `npm ci` has to run.
    pkg_dir = resolve_ts_package_dir(config.root, config.proto)
    workdir = "."
    if pkg_dir is not None:
        try:
            rel = pkg_dir.relative_to(config.root)
            workdir = str(rel).replace("\\", "/") or "."
        except ValueError:
            workdir = "."
    return f"""  proto-check-typescript:
    name: compile-protos --check (typescript)
    runs-on: ubuntu-latest
    steps:
      - uses: {CHECKOUT}

      - uses: {SETUP_NODE}
        with:
          node-version: '{ci.npm.node_version}'

      - name: Install TypeScript proto tooling
        run: npm ci
        working-directory: {workdir}

{_bootstrap_steps(ci)}
      - name: Verify generated TypeScript code is up to date
        run: {_rt(ci, "compile-protos --check --lang typescript")}
"""


def build_proto_check(config: SyncConfig, ci: CiConfig) -> str:
    """Drift check for generated protobuf/gRPC code, one job per language.

    Split per language on purpose: each job provisions only its own toolchain
    (protoc + Go plugins, or grpcio-tools, or npm), so the three run in parallel
    instead of serializing one job through every ecosystem's installer.
    """
    proto = config.proto
    if proto.is_empty:
        return ""

    missing = _proto_missing_pins(proto)
    if missing:
        raise ValueError(
            "proto-check.yml cannot be generated with unpinned tools:\n  - "
            + "\n  - ".join(missing)
            + "\nPin them, or add 'proto-check' to ci.skip_workflows to leave this "
              "workflow unmanaged."
        )

    paths: List[str] = ["versions.yaml", f"{proto.dir}/**"]
    for out in (proto.go, proto.python, proto.typescript):
        if out is not None:
            paths.append(f"{out.path}/**")

    jobs: List[str] = []
    if proto.go is not None:
        jobs.append(_proto_go_job(config, ci))
    if proto.python is not None:
        jobs.append(_proto_python_job(config, ci))
    if proto.typescript is not None:
        jobs.append(_proto_typescript_job(config, ci))

    return f"""{GENERATED_HEADER}
name: Proto Check

on:
  pull_request:
    paths:
{_format_paths_block(paths)}

concurrency:
  group: proto-check-${{{{ github.ref }}}}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
{chr(10).join(jobs)}"""


WORKFLOW_GENERATORS = (
    ("version-check.yml", build_version_check),
    ("proto-check.yml", build_proto_check),
    ("test-python.yml", build_test_python),
    ("test-npm.yml", build_test_npm),
    ("test-go.yml", build_test_go),
    ("publish-python.yml", build_publish_python),
    ("publish-npm.yml", build_publish_npm),
    ("build-docker.yml", build_build_docker),
)


def render_all(config: SyncConfig) -> dict:
    """Generate every workflow; empty string means 'no projects of that language'."""
    ci = config.ci
    out = {}
    for filename, fn in WORKFLOW_GENERATORS:
        out[filename] = fn(config, ci)
    return out


__all__ = [
    "GENERATED_HEADER",
    "WORKFLOW_GENERATORS",
    "build_version_check",
    "build_proto_check",
    "build_test_python",
    "build_test_npm",
    "build_test_go",
    "build_publish_python",
    "build_publish_npm",
    "build_build_docker",
    "render_all",
]
